import { GLOSSARY } from "./glossary";
import { PHYSICISTS } from "./physicists";
import type { Branch, Module, Topic } from "./types";

const CLASSICAL_MECHANICS_MODULES: readonly Module[] = [
  { slug: "kinematics-newton", title: "Kinematics & Newton", index: 1 },
  { slug: "conservation-laws", title: "Conservation Laws", index: 2 },
  { slug: "rotation-rigid-bodies", title: "Rotation & Rigid Bodies", index: 3 },
  { slug: "oscillations", title: "Oscillations", index: 4 },
  { slug: "waves", title: "Waves", index: 5 },
  { slug: "orbital-mechanics", title: "Orbital Mechanics", index: 6 },
  { slug: "fluids", title: "Fluids", index: 7 },
  { slug: "lagrangian-hamiltonian", title: "Lagrangian & Hamiltonian", index: 8 },
];

const CLASSICAL_MECHANICS_TOPICS: readonly Topic[] = [
  {
    slug: "the-simple-pendulum",
    title: "THE SIMPLE PENDULUM",
    eyebrow: "FIG.16 · OSCILLATIONS",
    subtitle: "Why every clock that ever ticked ticked the same way.",
    readingMinutes: 10,
    status: "live",
    module: "oscillations",
  },
  {
    slug: "beyond-small-angles",
    title: "BEYOND SMALL ANGLES",
    eyebrow: "FIG.17 · OSCILLATIONS",
    subtitle: "What the pendulum hides when you stop making approximations.",
    readingMinutes: 12,
    status: "live",
    module: "oscillations",
  },
  {
    slug: "oscillators-everywhere",
    title: "OSCILLATORS EVERYWHERE",
    eyebrow: "FIG.18 · OSCILLATIONS",
    subtitle: "The equation that runs half of physics.",
    readingMinutes: 12,
    status: "live",
    module: "oscillations",
  },
  {
    slug: "kepler",
    title: "THE LAWS OF PLANETS",
    eyebrow: "FIG.24 · ORBITAL MECHANICS",
    subtitle:
      "How a German astronomer broke the sky open with three sentences.",
    readingMinutes: 6,
    status: "live",
    module: "orbital-mechanics",
  },
  {
    slug: "universal-gravitation",
    title: "UNIVERSAL GRAVITATION",
    eyebrow: "FIG.25 · ORBITAL MECHANICS",
    subtitle:
      "The force that holds the Moon is the force that drops the apple.",
    readingMinutes: 12,
    status: "live",
    module: "orbital-mechanics",
  },
  {
    slug: "energy-in-orbit",
    title: "ENERGY IN ORBIT",
    eyebrow: "FIG.26 · ORBITAL MECHANICS",
    subtitle: "One equation tells you the speed at every point in space.",
    readingMinutes: 12,
    status: "live",
    module: "orbital-mechanics",
  },
  {
    slug: "tides-and-three-body",
    title: "TIDES AND THE THREE-BODY PROBLEM",
    eyebrow: "FIG.27 · ORBITAL MECHANICS",
    subtitle:
      "When gravity gets complicated, the universe gets interesting.",
    readingMinutes: 12,
    status: "live",
    module: "orbital-mechanics",
  },
    {
          slug: "motion-in-a-straight-line",
          title: "MOTION IN A STRAIGHT LINE",
          eyebrow: "FIG.01 · KINEMATICS & NEWTON",
          subtitle: "Position, velocity, acceleration — the three questions that gave physics its language.",
          readingMinutes: 10,
          status: "live",
          module: "kinematics-newton",
        },
    {
          slug: "vectors-and-projectile-motion",
          title: "VECTORS AND PROJECTILE MOTION",
          eyebrow: "FIG.02 · KINEMATICS & NEWTON",
          subtitle: "How Galileo split one hard problem into two easy ones — and why a cannonball traces a parabola.",
          readingMinutes: 10,
          status: "live",
          module: "kinematics-newton",
        },
    {
          slug: "newtons-three-laws",
          title: "NEWTON'S THREE LAWS",
          eyebrow: "FIG.03 · KINEMATICS & NEWTON",
          subtitle: "The three sentences that still run the world.",
          readingMinutes: 11,
          status: "live",
          module: "kinematics-newton",
        },
    {
          slug: "friction-and-drag",
          title: "FRICTION AND DRAG",
          eyebrow: "FIG.05 · KINEMATICS & NEWTON",
          subtitle: "The forces that quietly take the energy away — and, in doing so, run half of everyday physics.",
          readingMinutes: 12,
          status: "live",
          module: "kinematics-newton",
        },
    {
          slug: "energy-and-work",
          title: "ENERGY AND WORK",
          eyebrow: "FIG.07 · CONSERVATION LAWS",
          subtitle: "The universe keeps a ledger — and the totals always balance.",
          readingMinutes: 12,
          status: "live",
          module: "conservation-laws",
        },
    {
          slug: "momentum-and-collisions",
          title: "MOMENTUM AND COLLISIONS",
          eyebrow: "FIG.08 · CONSERVATION LAWS",
          subtitle: "The quantity nothing can create or destroy — only pass around.",
          readingMinutes: 13,
          status: "live",
          module: "conservation-laws",
        },
    {
          slug: "angular-momentum",
          title: "ANGULAR MOMENTUM",
          eyebrow: "FIG.09 · CONSERVATION LAWS",
          subtitle: "The quantity that makes skaters speed up, planets sweep out equal areas, and pulsars keep time.",
          readingMinutes: 13,
          status: "live",
          module: "conservation-laws",
        },
    {
          slug: "noethers-theorem",
          title: "NOETHER'S THEOREM",
          eyebrow: "FIG.10 · CONSERVATION LAWS",
          subtitle: "Every conservation law comes from a symmetry. Every symmetry gives you a conservation law.",
          readingMinutes: 14,
          status: "live",
          module: "conservation-laws",
        },
    {
          slug: "torque-and-rotational-dynamics",
          title: "TORQUE AND ROTATIONAL DYNAMICS",
          eyebrow: "FIG.11 · ROTATION & RIGID BODIES",
          subtitle: "Forces that turn instead of push — and the geometry that decides how much.",
          readingMinutes: 12,
          status: "live",
          module: "rotation-rigid-bodies",
        },
    {
          slug: "moment-of-inertia",
          title: "MOMENT OF INERTIA",
          eyebrow: "FIG.12 · ROTATION & RIGID BODIES",
          subtitle: "What mass becomes when you spin it.",
          readingMinutes: 13,
          status: "live",
          module: "rotation-rigid-bodies",
        },
    {
          slug: "gyroscopes-and-precession",
          title: "GYROSCOPES AND PRECESSION",
          eyebrow: "FIG.14 · ROTATION & RIGID BODIES",
          subtitle: "Why a spinning top refuses to fall.",
          readingMinutes: 14,
          status: "live",
          module: "rotation-rigid-bodies",
        },
    {
          slug: "the-wobbling-earth",
          title: "THE WOBBLING EARTH",
          eyebrow: "FIG.15 · ROTATION & RIGID BODIES",
          subtitle: "Precession, nutation, and the long memory of the planet.",
          readingMinutes: 14,
          status: "live",
          module: "rotation-rigid-bodies",
        },
    {
          slug: "the-wave-equation",
          title: "THE WAVE EQUATION",
          eyebrow: "FIG.20 · WAVES",
          subtitle: "The equation that runs every wave there is.",
          readingMinutes: 10,
          status: "live",
          module: "waves",
        },
    {
          slug: "standing-waves-and-modes",
          title: "STANDING WAVES AND MODES",
          eyebrow: "FIG.21 · WAVES",
          subtitle: "Why guitar strings only sing certain notes.",
          readingMinutes: 11,
          status: "live",
          module: "waves",
        },
    {
          slug: "doppler-and-shock-waves",
          title: "DOPPLER AND SHOCK WAVES",
          eyebrow: "FIG.22 · WAVES",
          subtitle: "What changes when the source moves.",
          readingMinutes: 11,
          status: "live",
          module: "waves",
        },
    {
          slug: "dispersion-and-group-velocity",
          title: "DISPERSION AND GROUP VELOCITY",
          eyebrow: "FIG.23 · WAVES",
          subtitle: "When different frequencies travel at different speeds.",
          readingMinutes: 12,
          status: "live",
          module: "waves",
        },
    {
          slug: "pressure-and-buoyancy",
          title: "PRESSURE AND BUOYANCY",
          eyebrow: "FIG.28 · FLUIDS",
          subtitle: "Why some things float.",
          readingMinutes: 12,
          status: "live",
          module: "fluids",
        },
    {
          slug: "bernoullis-principle",
          title: "BERNOULLI'S PRINCIPLE",
          eyebrow: "FIG.29 · FLUIDS",
          subtitle: "Faster fluids push less.",
          readingMinutes: 13,
          status: "live",
          module: "fluids",
        },
    {
          slug: "viscosity-and-reynolds-number",
          title: "VISCOSITY AND REYNOLDS NUMBER",
          eyebrow: "FIG.30 · FLUIDS",
          subtitle: "Honey, water, and the line between them.",
          readingMinutes: 13,
          status: "live",
          module: "fluids",
        },
    {
          slug: "turbulence",
          title: "TURBULENCE",
          eyebrow: "FIG.31 · FLUIDS",
          subtitle: "The last unsolved problem of classical physics.",
          readingMinutes: 12,
          status: "live",
          module: "fluids",
        },
    {
          slug: "the-principle-of-least-action",
          title: "THE PRINCIPLE OF LEAST ACTION",
          eyebrow: "FIG.32 · LAGRANGIAN & HAMILTONIAN",
          subtitle: "Nature picks the laziest path.",
          readingMinutes: 11,
          status: "live",
          module: "lagrangian-hamiltonian",
        },
    {
          slug: "the-lagrangian",
          title: "THE LAGRANGIAN",
          eyebrow: "FIG.33 · LAGRANGIAN & HAMILTONIAN",
          subtitle: "Mechanics rewritten as energy minus energy.",
          readingMinutes: 12,
          status: "live",
          module: "lagrangian-hamiltonian",
        },
    {
          slug: "the-hamiltonian",
          title: "THE HAMILTONIAN",
          eyebrow: "FIG.34 · LAGRANGIAN & HAMILTONIAN",
          subtitle: "Position and momentum, two halves of the same thing.",
          readingMinutes: 12,
          status: "live",
          module: "lagrangian-hamiltonian",
        },
    {
          slug: "phase-space",
          title: "PHASE SPACE",
          eyebrow: "FIG.35 · LAGRANGIAN & HAMILTONIAN",
          subtitle: "The space where every possible motion lives.",
          readingMinutes: 13,
          status: "live",
          module: "lagrangian-hamiltonian",
        },
  {
    slug: "circular-motion",
    title: "CIRCULAR MOTION",
    eyebrow: "FIG.04 · KINEMATICS & NEWTON",
    subtitle: "Why the string always pulls inward — and why the Moon never stops falling.",
    readingMinutes: 11,
    status: "live",
    module: "kinematics-newton",
  },
  {
    slug: "non-inertial-frames",
    title: "NON-INERTIAL REFERENCE FRAMES",
    eyebrow: "FIG.06 · KINEMATICS & NEWTON",
    subtitle: "Why a carousel feels like a force — and why the wind turns right in the northern hemisphere.",
    readingMinutes: 13,
    status: "live",
    module: "kinematics-newton",
  },
  {
    slug: "rolling-motion",
    title: "ROLLING MOTION",
    eyebrow: "FIG.13 · ROTATION & RIGID BODIES",
    subtitle: "What a wheel does that a puck can't — and why a hollow cylinder loses every race.",
    readingMinutes: 12,
    status: "live",
    module: "rotation-rigid-bodies",
  },
  {
    slug: "damped-and-driven-oscillations",
    title: "DAMPED & DRIVEN OSCILLATIONS",
    eyebrow: "FIG.19 · OSCILLATIONS",
    subtitle: "Why every real oscillator dies — and why, if you push it just right, it tries to kill you back.",
    readingMinutes: 13,
    status: "live",
    module: "oscillations",
  },
];

const ELECTROMAGNETISM_MODULES: readonly Module[] = [
  { slug: "electrostatics", title: "Electrostatics", index: 1 },
  { slug: "fields-in-matter", title: "Electric Fields in Matter", index: 2 },
  { slug: "magnetostatics", title: "Magnetostatics", index: 3 },
  { slug: "magnetism-in-matter", title: "Magnetic Fields in Matter", index: 4 },
  { slug: "induction", title: "Electrodynamics & Induction", index: 5 },
  { slug: "circuits", title: "Circuits", index: 6 },
  { slug: "maxwell", title: "Maxwell's Equations", index: 7 },
  { slug: "em-waves-vacuum", title: "EM Waves in Vacuum", index: 8 },
  { slug: "waves-in-matter-optics", title: "Waves in Matter & Optics", index: 9 },
  { slug: "radiation", title: "Radiation", index: 10 },
  { slug: "em-relativity", title: "EM & Relativity", index: 11 },
  { slug: "foundations", title: "Foundations", index: 12 },
];

const ELECTROMAGNETISM_TOPICS: readonly Topic[] = [
  {
    slug: "coulombs-law",
    title: "ELECTRIC CHARGE AND COULOMB'S LAW",
    eyebrow: "FIG.01 · ELECTROSTATICS",
    subtitle: "The force between two charges — and why it looks so much like gravity.",
    readingMinutes: 10,
    status: "live",
    module: "electrostatics",
  },
  {
    slug: "the-electric-field",
    title: "THE ELECTRIC FIELD",
    eyebrow: "FIG.02 · ELECTROSTATICS",
    subtitle: "When a force has a place of its own.",
    readingMinutes: 11,
    status: "live",
    module: "electrostatics",
  },
  {
    slug: "gauss-law",
    title: "GAUSS'S LAW",
    eyebrow: "FIG.03 · ELECTROSTATICS",
    subtitle: "The equation that turns symmetry into an answer.",
    readingMinutes: 12,
    status: "live",
    module: "electrostatics",
  },
  {
    slug: "electric-potential",
    title: "ELECTRIC POTENTIAL AND VOLTAGE",
    eyebrow: "FIG.04 · ELECTROSTATICS",
    subtitle: "Energy per charge, and the map every battery reads from.",
    readingMinutes: 11,
    status: "live",
    module: "electrostatics",
  },
  {
    slug: "capacitance-and-field-energy",
    title: "CAPACITANCE AND FIELD ENERGY",
    eyebrow: "FIG.05 · ELECTROSTATICS",
    subtitle: "Where the charge goes when you let go of the switch.",
    readingMinutes: 12,
    status: "live",
    module: "electrostatics",
  },
  {
    slug: "conductors-and-shielding",
    title: "CONDUCTORS AND THE FARADAY CAGE",
    eyebrow: "FIG.06 · ELECTROSTATICS",
    subtitle: "Why a metal box is the safest place in a lightning storm.",
    readingMinutes: 11,
    status: "live",
    module: "electrostatics",
  },
  {
    slug: "method-of-images",
    title: "THE METHOD OF IMAGES",
    eyebrow: "FIG.07 · ELECTROSTATICS",
    subtitle: "A trick that turns a hard problem into a symmetry.",
    readingMinutes: 12,
    status: "live",
    module: "electrostatics",
  },
  {
    slug: "polarization-and-bound-charges",
    title: "POLARIZATION AND BOUND CHARGES",
    eyebrow: "FIG.08 · ELECTRIC FIELDS IN MATTER",
    subtitle: "What happens when the charges can't leave, but can lean.",
    readingMinutes: 12,
    status: "live",
    module: "fields-in-matter",
  },
  {
    slug: "dielectrics-and-the-d-field",
    title: "DIELECTRICS AND THE D FIELD",
    eyebrow: "FIG.09 · ELECTRIC FIELDS IN MATTER",
    subtitle: "The extra field that only notices what's free.",
    readingMinutes: 12,
    status: "live",
    module: "fields-in-matter",
  },
  {
    slug: "boundary-conditions-at-interfaces",
    title: "BOUNDARY CONDITIONS AT INTERFACES",
    eyebrow: "FIG.10 · ELECTRIC FIELDS IN MATTER",
    subtitle: "What the field must do when the material changes.",
    readingMinutes: 10,
    status: "live",
    module: "fields-in-matter",
  },
  {
    slug: "piezo-and-ferroelectricity",
    title: "PIEZOELECTRICITY AND FERROELECTRICITY",
    eyebrow: "FIG.11 · ELECTRIC FIELDS IN MATTER",
    subtitle: "The crystals that remember which way they've been pushed.",
    readingMinutes: 11,
    status: "live",
    module: "fields-in-matter",
  },
  {
    slug: "the-lorentz-force",
    title: "CURRENTS AND THE LORENTZ FORCE",
    eyebrow: "FIG.12 · MAGNETOSTATICS",
    subtitle: "Why a moving charge feels what a still one doesn't.",
    readingMinutes: 12,
    status: "live",
    module: "magnetostatics",
  },
  {
    slug: "biot-savart-law",
    title: "THE BIOT–SAVART LAW",
    eyebrow: "FIG.13 · MAGNETOSTATICS",
    subtitle: "The magnetic analogue of Coulomb, one current element at a time.",
    readingMinutes: 12,
    status: "live",
    module: "magnetostatics",
  },
  {
    slug: "amperes-law",
    title: "AMPÈRE'S LAW",
    eyebrow: "FIG.14 · MAGNETOSTATICS",
    subtitle: "The shortcut when the current walks a straight line.",
    readingMinutes: 12,
    status: "live",
    module: "magnetostatics",
  },
  {
    slug: "the-vector-potential",
    title: "THE VECTOR POTENTIAL",
    eyebrow: "FIG.15 · MAGNETOSTATICS",
    subtitle: "The field behind the field.",
    readingMinutes: 13,
    status: "live",
    module: "magnetostatics",
  },
  {
    slug: "magnetic-dipoles",
    title: "MAGNETIC DIPOLES AND TORQUE ON LOOPS",
    eyebrow: "FIG.16 · MAGNETOSTATICS",
    subtitle: "Why a compass turns, in the language of fields.",
    readingMinutes: 11,
    status: "live",
    module: "magnetostatics",
  },
  {
    slug: "magnetization-and-the-h-field",
    title: "MAGNETIZATION AND THE H FIELD",
    eyebrow: "FIG.17 · MAGNETIC FIELDS IN MATTER",
    subtitle: "Matter's answer to an applied magnetic field.",
    readingMinutes: 12,
    status: "live",
    module: "magnetism-in-matter",
  },
  {
    slug: "dia-and-paramagnetism",
    title: "DIAMAGNETISM AND PARAMAGNETISM",
    eyebrow: "FIG.18 · MAGNETIC FIELDS IN MATTER",
    subtitle: "The quiet magnets hiding in almost everything.",
    readingMinutes: 11,
    status: "live",
    module: "magnetism-in-matter",
  },
  {
    slug: "ferromagnetism-and-hysteresis",
    title: "FERROMAGNETISM, DOMAINS, AND HYSTERESIS",
    eyebrow: "FIG.19 · MAGNETIC FIELDS IN MATTER",
    subtitle: "Why iron remembers, and why the memory can be erased.",
    readingMinutes: 13,
    status: "live",
    module: "magnetism-in-matter",
  },
  {
    slug: "superconductivity-and-meissner",
    title: "SUPERCONDUCTIVITY AND THE MEISSNER EFFECT",
    eyebrow: "FIG.20 · MAGNETIC FIELDS IN MATTER",
    subtitle: "When the field is not just weakened — it is thrown out.",
    readingMinutes: 12,
    status: "live",
    module: "magnetism-in-matter",
  },
  {
    slug: "faradays-law",
    title: "FARADAY'S LAW OF INDUCTION",
    eyebrow: "FIG.21 · ELECTRODYNAMICS & INDUCTION",
    subtitle: "A changing magnetic field brings an electric field with it.",
    readingMinutes: 12,
    status: "live",
    module: "induction",
  },
  {
    slug: "lenz-law-and-motional-emf",
    title: "LENZ'S LAW AND MOTIONAL EMF",
    eyebrow: "FIG.22 · ELECTRODYNAMICS & INDUCTION",
    subtitle: "Nature pushes back against the change that caused it.",
    readingMinutes: 11,
    status: "live",
    module: "induction",
  },
  {
    slug: "self-and-mutual-inductance",
    title: "SELF AND MUTUAL INDUCTANCE",
    eyebrow: "FIG.23 · ELECTRODYNAMICS & INDUCTION",
    subtitle: "Why a coil resists its own changing current.",
    readingMinutes: 12,
    status: "live",
    module: "induction",
  },
  {
    slug: "energy-in-magnetic-fields",
    title: "ENERGY IN MAGNETIC FIELDS",
    eyebrow: "FIG.24 · ELECTRODYNAMICS & INDUCTION",
    subtitle: "Where the energy goes when the current ramps up.",
    readingMinutes: 11,
    status: "live",
    module: "induction",
  },
  {
    slug: "eddy-currents",
    title: "EDDY CURRENTS AND MAGNETIC BRAKING",
    eyebrow: "FIG.25 · ELECTRODYNAMICS & INDUCTION",
    subtitle: "The invisible circuits that stop a falling magnet.",
    readingMinutes: 11,
    status: "live",
    module: "induction",
  },
  {
    slug: "dc-circuits-and-kirchhoff",
    title: "DC CIRCUITS AND KIRCHHOFF'S LAWS",
    eyebrow: "FIG.26 · CIRCUITS",
    subtitle: "The two sentences that solve almost every schematic.",
    readingMinutes: 12,
    status: "live",
    module: "circuits",
  },
  {
    slug: "rc-circuits",
    title: "RC CIRCUITS AND THE CHARGING CURVE",
    eyebrow: "FIG.27 · CIRCUITS",
    subtitle: "Why the capacitor never quite gets there, and always almost does.",
    readingMinutes: 11,
    status: "live",
    module: "circuits",
  },
  {
    slug: "rl-circuits",
    title: "RL CIRCUITS",
    eyebrow: "FIG.28 · CIRCUITS",
    subtitle: "The coil's version of hesitation.",
    readingMinutes: 10,
    status: "live",
    module: "circuits",
  },
  {
    slug: "rlc-circuits-and-resonance",
    title: "RLC CIRCUITS AND RESONANCE",
    eyebrow: "FIG.29 · CIRCUITS",
    subtitle: "Two stores of energy, one frequency that loves them both.",
    readingMinutes: 12,
    status: "live",
    module: "circuits",
  },
  {
    slug: "ac-circuits-and-phasors",
    title: "AC CIRCUITS, PHASORS, AND IMPEDANCE",
    eyebrow: "FIG.30 · CIRCUITS",
    subtitle: "Rotation as the secret of every wall socket.",
    readingMinutes: 13,
    status: "live",
    module: "circuits",
  },
  {
    slug: "transformers",
    title: "TRANSFORMERS AND POWER TRANSMISSION",
    eyebrow: "FIG.31 · CIRCUITS",
    subtitle: "How one coil teaches another what voltage to be.",
    readingMinutes: 11,
    status: "live",
    module: "circuits",
  },
  {
    slug: "transmission-lines",
    title: "TRANSMISSION LINES AND IMPEDANCE MATCHING",
    eyebrow: "FIG.32 · CIRCUITS",
    subtitle: "When the wire becomes long enough to matter.",
    readingMinutes: 13,
    status: "live",
    module: "circuits",
  },
  {
    slug: "displacement-current",
    title: "DISPLACEMENT CURRENT",
    eyebrow: "FIG.33 · MAXWELL'S EQUATIONS",
    subtitle: "The missing term Maxwell put in, and the universe it unlocked.",
    readingMinutes: 12,
    status: "live",
    module: "maxwell",
  },
  {
    slug: "the-four-equations",
    title: "THE FOUR EQUATIONS, TOGETHER",
    eyebrow: "FIG.34 · MAXWELL'S EQUATIONS",
    subtitle: "The most important four lines in physics.",
    readingMinutes: 13,
    status: "live",
    module: "maxwell",
  },
  {
    slug: "gauge-freedom-and-potentials",
    title: "GAUGE FREEDOM AND THE POTENTIALS",
    eyebrow: "FIG.35 · MAXWELL'S EQUATIONS",
    subtitle: "The parts of the potential the field can't see.",
    readingMinutes: 13,
    status: "live",
    module: "maxwell",
  },
  {
    slug: "the-poynting-vector",
    title: "THE POYNTING VECTOR",
    eyebrow: "FIG.36 · MAXWELL'S EQUATIONS",
    subtitle: "Where the energy in a field is flowing, right now.",
    readingMinutes: 11,
    status: "live",
    module: "maxwell",
  },
  {
    slug: "maxwell-stress-tensor",
    title: "MOMENTUM AND THE MAXWELL STRESS TENSOR",
    eyebrow: "FIG.37 · MAXWELL'S EQUATIONS",
    subtitle: "Fields carry momentum — and push on what they touch.",
    readingMinutes: 13,
    status: "live",
    module: "maxwell",
  },
  {
    slug: "deriving-the-em-wave-equation",
    title: "DERIVING THE EM WAVE EQUATION",
    eyebrow: "FIG.38 · EM WAVES IN VACUUM",
    subtitle: "Four equations, two fields, and light falling out the other side.",
    readingMinutes: 11,
    status: "live",
    module: "em-waves-vacuum",
  },
  {
    slug: "plane-waves-and-polarization",
    title: "PLANE WAVES AND POLARIZATION",
    eyebrow: "FIG.39 · EM WAVES IN VACUUM",
    subtitle: "The shape of a ray of light, written in two transverse fields.",
    readingMinutes: 12,
    status: "live",
    module: "em-waves-vacuum",
  },
  {
    slug: "radiation-pressure",
    title: "ENERGY, MOMENTUM, AND RADIATION PRESSURE",
    eyebrow: "FIG.40 · EM WAVES IN VACUUM",
    subtitle: "Light pushes. Measurably.",
    readingMinutes: 11,
    status: "live",
    module: "em-waves-vacuum",
  },
  {
    slug: "the-electromagnetic-spectrum",
    title: "THE ELECTROMAGNETIC SPECTRUM",
    eyebrow: "FIG.41 · EM WAVES IN VACUUM",
    subtitle: "One equation, every wavelength from radio to gamma.",
    readingMinutes: 10,
    status: "live",
    module: "em-waves-vacuum",
  },
  {
    slug: "index-of-refraction",
    title: "INDEX OF REFRACTION",
    eyebrow: "FIG.42 · WAVES IN MATTER & OPTICS",
    subtitle: "What slows light down when it has somewhere to be.",
    readingMinutes: 11,
    status: "live",
    module: "waves-in-matter-optics",
  },
  {
    slug: "skin-depth-in-conductors",
    title: "SKIN DEPTH IN CONDUCTORS",
    eyebrow: "FIG.43 · WAVES IN MATTER & OPTICS",
    subtitle: "How deep a radio wave can actually get into a metal.",
    readingMinutes: 11,
    status: "live",
    module: "waves-in-matter-optics",
  },
  {
    slug: "fresnel-equations",
    title: "THE FRESNEL EQUATIONS",
    eyebrow: "FIG.44 · WAVES IN MATTER & OPTICS",
    subtitle: "What reflects, what goes through, and at what angle.",
    readingMinutes: 13,
    status: "live",
    module: "waves-in-matter-optics",
  },
  {
    slug: "total-internal-reflection",
    title: "TOTAL INTERNAL REFLECTION",
    eyebrow: "FIG.45 · WAVES IN MATTER & OPTICS",
    subtitle: "The mirror made of an angle.",
    readingMinutes: 11,
    status: "live",
    module: "waves-in-matter-optics",
  },
  {
    slug: "optical-dispersion",
    title: "OPTICAL DISPERSION",
    eyebrow: "FIG.46 · WAVES IN MATTER & OPTICS",
    subtitle: "Why a prism splits white light — and why a rainbow has an order.",
    readingMinutes: 11,
    status: "live",
    module: "waves-in-matter-optics",
  },
  {
    slug: "geometric-optics",
    title: "GEOMETRIC OPTICS",
    eyebrow: "FIG.47 · WAVES IN MATTER & OPTICS",
    subtitle: "When the wavelength is small enough to forget.",
    readingMinutes: 12,
    status: "live",
    module: "waves-in-matter-optics",
  },
  {
    slug: "interference",
    title: "INTERFERENCE",
    eyebrow: "FIG.48 · WAVES IN MATTER & OPTICS",
    subtitle: "Two waves that know how to add — and how to cancel.",
    readingMinutes: 12,
    status: "live",
    module: "waves-in-matter-optics",
  },
  {
    slug: "diffraction-and-the-double-slit",
    title: "DIFFRACTION AND THE DOUBLE SLIT",
    eyebrow: "FIG.49 · WAVES IN MATTER & OPTICS",
    subtitle: "What a wave does when a wall gets in the way.",
    readingMinutes: 13,
    status: "live",
    module: "waves-in-matter-optics",
  },
  {
    slug: "polarization-phenomena",
    title: "POLARIZATION, BREWSTER, AND BIREFRINGENCE",
    eyebrow: "FIG.50 · WAVES IN MATTER & OPTICS",
    subtitle: "When the direction the field points starts to matter.",
    readingMinutes: 12,
    status: "live",
    module: "waves-in-matter-optics",
  },
  {
    slug: "waveguides-and-fibers",
    title: "WAVEGUIDES AND OPTICAL FIBERS",
    eyebrow: "FIG.51 · WAVES IN MATTER & OPTICS",
    subtitle: "How to keep light inside a pipe for a thousand kilometers.",
    readingMinutes: 12,
    status: "live",
    module: "waves-in-matter-optics",
  },
  {
    slug: "larmor-formula",
    title: "THE LARMOR FORMULA",
    eyebrow: "FIG.52 · RADIATION",
    subtitle: "Why every accelerating charge leaves light behind.",
    readingMinutes: 11,
    status: "live",
    module: "radiation",
  },
  {
    slug: "electric-dipole-radiation",
    title: "ELECTRIC DIPOLE RADIATION",
    eyebrow: "FIG.53 · RADIATION",
    subtitle: "The simplest antenna in the universe.",
    readingMinutes: 12,
    status: "live",
    module: "radiation",
  },
  {
    slug: "antennas-and-radio",
    title: "ANTENNAS AND RADIO",
    eyebrow: "FIG.54 · RADIATION",
    subtitle: "The difference between a wire and a broadcast.",
    readingMinutes: 12,
    status: "live",
    module: "radiation",
  },
  {
    slug: "synchrotron-radiation",
    title: "SYNCHROTRON RADIATION",
    eyebrow: "FIG.55 · RADIATION",
    subtitle: "Light made on purpose by bending electrons in a circle.",
    readingMinutes: 11,
    status: "live",
    module: "radiation",
  },
  {
    slug: "bremsstrahlung",
    title: "BREMSSTRAHLUNG",
    eyebrow: "FIG.56 · RADIATION",
    subtitle: "The light that comes out when a charge gets in the way of itself.",
    readingMinutes: 10,
    status: "live",
    module: "radiation",
  },
  {
    slug: "radiation-reaction",
    title: "RADIATION REACTION",
    eyebrow: "FIG.57 · RADIATION",
    subtitle: "The force that a charge exerts back on itself.",
    readingMinutes: 13,
    status: "live",
    module: "radiation",
  },
  {
    slug: "charge-invariance",
    title: "CHARGE IS INVARIANT",
    eyebrow: "FIG.58 · EM AND RELATIVITY",
    subtitle: "The one quantity every observer must agree on.",
    readingMinutes: 10,
    status: "live",
    module: "em-relativity",
  },
  {
    slug: "e-and-b-under-lorentz",
    title: "E AND B UNDER A LORENTZ BOOST",
    eyebrow: "FIG.59 · EM AND RELATIVITY",
    subtitle:
      "What looks like a magnet to you looks like an electric field to someone moving past.",
    readingMinutes: 13,
    status: "live",
    module: "em-relativity",
  },
  {
    slug: "the-electromagnetic-field-tensor",
    title: "THE ELECTROMAGNETIC FIELD TENSOR",
    eyebrow: "FIG.60 · EM AND RELATIVITY",
    subtitle: "Six numbers, one object, the full relativistic story.",
    readingMinutes: 13,
    status: "live",
    module: "em-relativity",
  },
  {
    slug: "magnetism-as-relativistic-electrostatics",
    title: "MAGNETISM AS RELATIVISTIC ELECTROSTATICS",
    eyebrow: "FIG.61 · EM AND RELATIVITY",
    subtitle: "The reveal: there is no second force.",
    readingMinutes: 14,
    status: "live",
    module: "em-relativity",
  },
  {
    slug: "four-potential-and-em-lagrangian",
    title: "THE FOUR-POTENTIAL AND EM LAGRANGIAN",
    eyebrow: "FIG.62 · EM AND RELATIVITY",
    subtitle: "Electromagnetism rewritten as a principle of least action.",
    readingMinutes: 13,
    status: "live",
    module: "em-relativity",
  },
  {
    slug: "gauge-theory-origins",
    title: "GAUGE INVARIANCE AND THE BIRTH OF GAUGE THEORIES",
    eyebrow: "FIG.63 · FOUNDATIONS",
    subtitle: "The symmetry that became the template for every force.",
    readingMinutes: 13,
    status: "live",
    module: "foundations",
  },
  {
    slug: "aharonov-bohm-effect",
    title: "THE AHARONOV–BOHM EFFECT",
    eyebrow: "FIG.64 · FOUNDATIONS",
    subtitle: "When the potential matters even where the field is zero.",
    readingMinutes: 12,
    status: "live",
    module: "foundations",
  },
  {
    slug: "magnetic-monopoles-and-duality",
    title: "MAGNETIC MONOPOLES AND DUALITY",
    eyebrow: "FIG.65 · FOUNDATIONS",
    subtitle: "The symmetric version of Maxwell, and the particle we haven't found.",
    readingMinutes: 11,
    status: "live",
    module: "foundations",
  },
  {
    slug: "classical-limit-of-qed",
    title: "THE CLASSICAL LIMIT OF QED",
    eyebrow: "FIG.66 · FOUNDATIONS",
    subtitle: "Where classical electromagnetism ends, and what replaces it.",
    readingMinutes: 12,
    status: "live",
    module: "foundations",
  },
];

const RELATIVITY_MODULES: readonly Module[] = [
  { slug: "sr-foundations", title: "SR Foundations", index: 1 },
  { slug: "sr-kinematics", title: "SR Kinematics", index: 2 },
  { slug: "spacetime-geometry", title: "Spacetime Geometry", index: 3 },
  { slug: "relativistic-dynamics", title: "Relativistic Dynamics", index: 4 },
  { slug: "sr-applications", title: "SR Applications and Paradoxes", index: 5 },
  { slug: "equivalence-principle", title: "The Equivalence Principle", index: 6 },
  { slug: "tensor-calculus", title: "Curved Spacetime and Tensor Calculus", index: 7 },
  { slug: "curvature-and-efe", title: "Riemann Curvature and Einstein's Equations", index: 8 },
  { slug: "schwarzschild-and-tests", title: "Schwarzschild and the Classical Tests", index: 9 },
  { slug: "black-holes", title: "Black Holes", index: 10 },
  { slug: "gravitational-waves", title: "Gravitational Waves", index: 11 },
  { slug: "cosmology", title: "Cosmology", index: 12 },
  { slug: "frontiers", title: "Frontiers", index: 13 },
];

const RELATIVITY_TOPICS: readonly Topic[] = [
  // §01 SR Foundations — FIG.01–05 (live)
  { slug: "galilean-relativity", title: "GALILEAN RELATIVITY AND THE FRAME PROBLEM", eyebrow: "FIG.01 · SR FOUNDATIONS", subtitle: "Why Newton's universe needed an observer who never moved.", readingMinutes: 9, status: "live", module: "sr-foundations" },
  { slug: "maxwell-and-the-speed-of-light", title: "MAXWELL AND THE SPEED OF LIGHT", eyebrow: "FIG.02 · SR FOUNDATIONS", subtitle: "The constant hiding in two SI numbers, and what it didn't depend on.", readingMinutes: 10, status: "live", module: "sr-foundations" },
  { slug: "michelson-morley", title: "THE MICHELSON-MORLEY EXPERIMENT", eyebrow: "FIG.03 · SR FOUNDATIONS", subtitle: "An interferometer asks the wind which way it blows, and gets no answer.", readingMinutes: 11, status: "live", module: "sr-foundations" },
  { slug: "einsteins-two-postulates", title: "EINSTEIN'S TWO POSTULATES", eyebrow: "FIG.04 · SR FOUNDATIONS", subtitle: "Drop one assumption, take one fact at face value, get a new universe.", readingMinutes: 10, status: "live", module: "sr-foundations" },
  { slug: "relative-simultaneity", title: "THE RELATIVITY OF SIMULTANEITY", eyebrow: "FIG.05 · SR FOUNDATIONS", subtitle: "Two lightning bolts strike — and the train passenger disagrees with you about which came first.", readingMinutes: 11, status: "live", module: "sr-foundations" },
  // §02 SR Kinematics — FIG.06–10 (live)
  { slug: "time-dilation", title: "TIME DILATION", eyebrow: "FIG.06 · SR KINEMATICS", subtitle: "Why a moving clock ticks slower — and why this is not an illusion.", readingMinutes: 12, status: "live", module: "sr-kinematics" },
  { slug: "length-contraction", title: "LENGTH CONTRACTION", eyebrow: "FIG.07 · SR KINEMATICS", subtitle: "Why a moving rod is shorter — and why no one moving with it can tell.", readingMinutes: 11, status: "live", module: "sr-kinematics" },
  { slug: "the-lorentz-transformation", title: "THE LORENTZ TRANSFORMATION", eyebrow: "FIG.08 · SR KINEMATICS", subtitle: "The four lines of algebra that replaced Galileo.", readingMinutes: 13, status: "live", module: "sr-kinematics" },
  { slug: "velocity-addition", title: "RELATIVISTIC VELOCITY ADDITION", eyebrow: "FIG.09 · SR KINEMATICS", subtitle: "Why nothing made of matter ever crosses 299,792,458 m/s.", readingMinutes: 11, status: "live", module: "sr-kinematics" },
  { slug: "relativistic-doppler", title: "THE RELATIVISTIC DOPPLER EFFECT", eyebrow: "FIG.10 · SR KINEMATICS", subtitle: "What the source's color tells you about its motion through spacetime.", readingMinutes: 11, status: "live", module: "sr-kinematics" },
  // §03 Spacetime geometry — FIG.11–15 (coming-soon)
  { slug: "spacetime-diagrams", title: "SPACETIME DIAGRAMS AND WORLDLINES", eyebrow: "FIG.11 · SPACETIME GEOMETRY", subtitle: "Draw a clock's life as a single line on a piece of paper.", readingMinutes: 11, status: "coming-soon", module: "spacetime-geometry" },
  { slug: "the-invariant-interval", title: "THE INVARIANT INTERVAL", eyebrow: "FIG.12 · SPACETIME GEOMETRY", subtitle: "The one quantity every observer must agree on.", readingMinutes: 12, status: "coming-soon", module: "spacetime-geometry" },
  { slug: "light-cones-and-causality", title: "LIGHT CONES AND CAUSALITY", eyebrow: "FIG.13 · SPACETIME GEOMETRY", subtitle: "The shape spacetime gives \"before\" and \"after\" — and \"neither.\"", readingMinutes: 11, status: "coming-soon", module: "spacetime-geometry" },
  { slug: "four-vectors-and-proper-time", title: "FOUR-VECTORS AND PROPER TIME", eyebrow: "FIG.14 · SPACETIME GEOMETRY", subtitle: "The invariant heartbeat of every traveler in spacetime.", readingMinutes: 12, status: "coming-soon", module: "spacetime-geometry" },
  { slug: "the-twin-paradox", title: "THE TWIN PARADOX", eyebrow: "FIG.15 · SPACETIME GEOMETRY", subtitle: "The longest worldline in spacetime is also the shortest in proper time.", readingMinutes: 13, status: "coming-soon", module: "spacetime-geometry" },
  // §04 Relativistic dynamics — FIG.16–20 (coming-soon)
  { slug: "four-momentum", title: "FOUR-MOMENTUM", eyebrow: "FIG.16 · RELATIVISTIC DYNAMICS", subtitle: "Energy and momentum, packaged into one object that transforms as a vector.", readingMinutes: 12, status: "coming-soon", module: "relativistic-dynamics" },
  { slug: "mass-energy-equivalence", title: "MASS-ENERGY EQUIVALENCE", eyebrow: "FIG.17 · RELATIVISTIC DYNAMICS", subtitle: "Why a hot cup of coffee weighs more than a cold one.", readingMinutes: 13, status: "coming-soon", module: "relativistic-dynamics" },
  { slug: "relativistic-collisions", title: "RELATIVISTIC COLLISIONS", eyebrow: "FIG.18 · RELATIVISTIC DYNAMICS", subtitle: "Conservation of four-momentum, and what changes when speeds get high.", readingMinutes: 12, status: "coming-soon", module: "relativistic-dynamics" },
  { slug: "compton-scattering", title: "COMPTON SCATTERING", eyebrow: "FIG.19 · RELATIVISTIC DYNAMICS", subtitle: "The 1923 experiment that finally made photons mechanical.", readingMinutes: 11, status: "coming-soon", module: "relativistic-dynamics" },
  { slug: "threshold-energy-and-pair-production", title: "THRESHOLD ENERGY AND PAIR PRODUCTION", eyebrow: "FIG.20 · RELATIVISTIC DYNAMICS", subtitle: "Why a 1.022 MeV gamma ray can become two electrons but a 511 keV one cannot.", readingMinutes: 12, status: "coming-soon", module: "relativistic-dynamics" },
  // §05 SR applications — FIG.21–24 (coming-soon)
  { slug: "the-barn-pole-paradox", title: "THE BARN-POLE PARADOX", eyebrow: "FIG.21 · SR APPLICATIONS", subtitle: "Two observers, two answers, no contradiction.", readingMinutes: 11, status: "coming-soon", module: "sr-applications" },
  { slug: "bells-spaceship-paradox", title: "BELL'S SPACESHIP PARADOX", eyebrow: "FIG.22 · SR APPLICATIONS", subtitle: "A string between two synchronized rockets, and the geometry that snaps it.", readingMinutes: 11, status: "coming-soon", module: "sr-applications" },
  { slug: "gps-as-relativity", title: "GPS AS A WORKING RELATIVITY EXPERIMENT", eyebrow: "FIG.23 · SR APPLICATIONS", subtitle: "Without two corrections, your position drifts ten kilometers a day.", readingMinutes: 12, status: "coming-soon", module: "sr-applications" },
  { slug: "precision-tests-of-sr", title: "PRECISION TESTS OF LORENTZ INVARIANCE", eyebrow: "FIG.24 · SR APPLICATIONS", subtitle: "What happens when a theory survives a hundred years of being checked.", readingMinutes: 11, status: "coming-soon", module: "sr-applications" },
  // §06 Equivalence principle — FIG.25–28 (coming-soon)
  { slug: "inertial-vs-gravitational-mass", title: "INERTIAL VS GRAVITATIONAL MASS", eyebrow: "FIG.25 · EQUIVALENCE PRINCIPLE", subtitle: "Why two completely different definitions give the same number to thirteen decimal places.", readingMinutes: 12, status: "coming-soon", module: "equivalence-principle" },
  { slug: "einsteins-elevator", title: "EINSTEIN'S ELEVATOR", eyebrow: "FIG.26 · EQUIVALENCE PRINCIPLE", subtitle: "A free-falling lab is a frame where gravity has been canceled.", readingMinutes: 11, status: "coming-soon", module: "equivalence-principle" },
  { slug: "gravitational-redshift", title: "GRAVITATIONAL REDSHIFT", eyebrow: "FIG.27 · EQUIVALENCE PRINCIPLE", subtitle: "Climb out of a gravity well and your photons get tired.", readingMinutes: 12, status: "coming-soon", module: "equivalence-principle" },
  { slug: "gravity-as-geometry", title: "GRAVITY AS GEOMETRY", eyebrow: "FIG.28 · EQUIVALENCE PRINCIPLE", subtitle: "The equivalence principle's geometric implication: there is no force, only curvature.", readingMinutes: 12, status: "coming-soon", module: "equivalence-principle" },
  // §07 Tensor calculus — FIG.29–33 (coming-soon)
  { slug: "manifolds-and-tangent-spaces", title: "MANIFOLDS AND TANGENT SPACES", eyebrow: "FIG.29 · TENSOR CALCULUS", subtitle: "Curved spaces and the flat ones that approximate them point by point.", readingMinutes: 13, status: "coming-soon", module: "tensor-calculus" },
  { slug: "tensors-on-curved-space", title: "TENSORS ON CURVED SPACE", eyebrow: "FIG.30 · TENSOR CALCULUS", subtitle: "Indexed objects that don't lie about which way they point.", readingMinutes: 13, status: "coming-soon", module: "tensor-calculus" },
  { slug: "the-metric-tensor", title: "THE METRIC TENSOR", eyebrow: "FIG.31 · TENSOR CALCULUS", subtitle: "The object that turns coordinate differences into actual distances.", readingMinutes: 13, status: "coming-soon", module: "tensor-calculus" },
  { slug: "christoffels-and-parallel-transport", title: "CHRISTOFFELS AND PARALLEL TRANSPORT", eyebrow: "FIG.32 · TENSOR CALCULUS", subtitle: "The connection that says what \"stays parallel\" means on a curved surface.", readingMinutes: 13, status: "coming-soon", module: "tensor-calculus" },
  { slug: "geodesics", title: "GEODESICS", eyebrow: "FIG.33 · TENSOR CALCULUS", subtitle: "The straightest possible lines, and why falling apples follow them.", readingMinutes: 13, status: "coming-soon", module: "tensor-calculus" },
  // §08 Curvature & EFE — FIG.34–38 (coming-soon)
  { slug: "the-riemann-tensor", title: "THE RIEMANN CURVATURE TENSOR", eyebrow: "FIG.34 · CURVATURE & EFE", subtitle: "Twenty independent numbers per point that say exactly how a space is bent.", readingMinutes: 13, status: "coming-soon", module: "curvature-and-efe" },
  { slug: "ricci-and-the-einstein-tensor", title: "RICCI, SCALAR CURVATURE, AND THE EINSTEIN TENSOR", eyebrow: "FIG.35 · CURVATURE & EFE", subtitle: "The contractions that make a divergence-free curvature object.", readingMinutes: 12, status: "coming-soon", module: "curvature-and-efe" },
  { slug: "the-stress-energy-tensor", title: "THE STRESS-ENERGY TENSOR", eyebrow: "FIG.36 · CURVATURE & EFE", subtitle: "Energy, momentum, pressure, and stress, all in one object.", readingMinutes: 12, status: "coming-soon", module: "curvature-and-efe" },
  { slug: "einsteins-field-equations", title: "EINSTEIN'S FIELD EQUATIONS", eyebrow: "FIG.37 · CURVATURE & EFE", subtitle: "Spacetime tells matter how to move; matter tells spacetime how to curve.", readingMinutes: 14, status: "coming-soon", module: "curvature-and-efe" },
  { slug: "the-newtonian-limit", title: "THE NEWTONIAN LIMIT", eyebrow: "FIG.38 · CURVATURE & EFE", subtitle: "Where GR gives back Newton, and where it refuses.", readingMinutes: 11, status: "coming-soon", module: "curvature-and-efe" },
  // §09 Schwarzschild + tests — FIG.39–43 (coming-soon)
  { slug: "the-schwarzschild-metric", title: "THE SCHWARZSCHILD METRIC", eyebrow: "FIG.39 · SCHWARZSCHILD + TESTS", subtitle: "The first exact solution to Einstein's equations, solved in a trench in 1915.", readingMinutes: 13, status: "coming-soon", module: "schwarzschild-and-tests" },
  { slug: "mercurys-perihelion", title: "MERCURY'S PERIHELION", eyebrow: "FIG.40 · SCHWARZSCHILD + TESTS", subtitle: "A 43-arcsecond-per-century mismatch that closed seventy years of guesswork.", readingMinutes: 12, status: "coming-soon", module: "schwarzschild-and-tests" },
  { slug: "light-deflection-and-lensing", title: "LIGHT DEFLECTION AND GRAVITATIONAL LENSING", eyebrow: "FIG.41 · SCHWARZSCHILD + TESTS", subtitle: "A May 1919 eclipse photograph, Einstein on the front page of every newspaper.", readingMinutes: 12, status: "coming-soon", module: "schwarzschild-and-tests" },
  { slug: "shapiro-delay", title: "THE SHAPIRO TIME DELAY", eyebrow: "FIG.42 · SCHWARZSCHILD + TESTS", subtitle: "Light slowed not by mass but by the geometry the mass produces.", readingMinutes: 11, status: "coming-soon", module: "schwarzschild-and-tests" },
  { slug: "the-classical-tests-summary", title: "THE CLASSICAL TESTS — A WHOLE THEORY ON TRIAL", eyebrow: "FIG.43 · SCHWARZSCHILD + TESTS", subtitle: "Four independent predictions, four confirmed observations, one theory standing.", readingMinutes: 10, status: "coming-soon", module: "schwarzschild-and-tests" },
  // §10 Black holes — FIG.44–49 (coming-soon)
  { slug: "the-event-horizon", title: "THE EVENT HORIZON", eyebrow: "FIG.44 · BLACK HOLES", subtitle: "The one-way membrane, what it looks like to the infaller, and what it doesn't.", readingMinutes: 13, status: "coming-soon", module: "black-holes" },
  { slug: "kerr-and-the-ergosphere", title: "KERR BLACK HOLES AND THE ERGOSPHERE", eyebrow: "FIG.45 · BLACK HOLES", subtitle: "Spinning spacetime drags everything inside it along for the ride.", readingMinutes: 12, status: "coming-soon", module: "black-holes" },
  { slug: "penrose-diagrams", title: "PENROSE DIAGRAMS AND CAUSAL STRUCTURE", eyebrow: "FIG.46 · BLACK HOLES", subtitle: "Compactify infinity; learn what a black hole's interior actually looks like.", readingMinutes: 13, status: "coming-soon", module: "black-holes" },
  { slug: "no-hair-theorem", title: "THE NO-HAIR THEOREM", eyebrow: "FIG.47 · BLACK HOLES", subtitle: "Three numbers describe every black hole: mass, charge, spin.", readingMinutes: 11, status: "coming-soon", module: "black-holes" },
  { slug: "black-hole-thermodynamics", title: "BLACK-HOLE THERMODYNAMICS", eyebrow: "FIG.48 · BLACK HOLES", subtitle: "The area theorem, Bekenstein entropy, and why a black hole is a thermal object.", readingMinutes: 12, status: "coming-soon", module: "black-holes" },
  { slug: "hawking-radiation", title: "HAWKING RADIATION", eyebrow: "FIG.49 · BLACK HOLES", subtitle: "A semiclassical preview: even the blackest hole evaporates.", readingMinutes: 12, status: "coming-soon", module: "black-holes" },
  // §11 Gravitational waves — FIG.50–53 (coming-soon)
  { slug: "linearized-gravity", title: "LINEARIZED GRAVITY", eyebrow: "FIG.50 · GRAVITATIONAL WAVES", subtitle: "Small ripples in a flat background, governed by a wave equation.", readingMinutes: 12, status: "coming-soon", module: "gravitational-waves" },
  { slug: "polarization-modes", title: "THE TWO POLARIZATIONS — PLUS AND CROSS", eyebrow: "FIG.51 · GRAVITATIONAL WAVES", subtitle: "What a gravitational wave does to a ring of free-floating test masses.", readingMinutes: 11, status: "coming-soon", module: "gravitational-waves" },
  { slug: "binary-inspiral-and-the-chirp", title: "BINARY INSPIRAL AND THE CHIRP", eyebrow: "FIG.52 · GRAVITATIONAL WAVES", subtitle: "Two black holes spiraling in; the waveform's frequency rises like a chirp.", readingMinutes: 12, status: "coming-soon", module: "gravitational-waves" },
  { slug: "ligo-and-multi-messenger", title: "LIGO AND MULTI-MESSENGER ASTRONOMY", eyebrow: "FIG.53 · GRAVITATIONAL WAVES", subtitle: "GW150914, GW170817, and what it means to hear the universe instead of seeing it.", readingMinutes: 12, status: "coming-soon", module: "gravitational-waves" },
  // §12 Cosmology — FIG.54–58 (coming-soon)
  { slug: "the-flrw-metric", title: "THE FLRW METRIC", eyebrow: "FIG.54 · COSMOLOGY", subtitle: "The geometry the universe picked out for itself.", readingMinutes: 12, status: "coming-soon", module: "cosmology" },
  { slug: "friedmann-equations", title: "FRIEDMANN'S EQUATIONS", eyebrow: "FIG.55 · COSMOLOGY", subtitle: "Two ODEs that govern the expansion of everything.", readingMinutes: 13, status: "coming-soon", module: "cosmology" },
  { slug: "hubble-and-cosmological-redshift", title: "HUBBLE AND COSMOLOGICAL REDSHIFT", eyebrow: "FIG.56 · COSMOLOGY", subtitle: "Why distant galaxies' light is stretched, and what is doing the stretching.", readingMinutes: 12, status: "coming-soon", module: "cosmology" },
  { slug: "the-cmb-and-nucleosynthesis", title: "THE CMB AND BIG BANG NUCLEOSYNTHESIS", eyebrow: "FIG.57 · COSMOLOGY", subtitle: "The leftover heat and the first three minutes' worth of helium.", readingMinutes: 13, status: "coming-soon", module: "cosmology" },
  { slug: "dark-matter-and-dark-energy", title: "DARK MATTER AND DARK ENERGY", eyebrow: "FIG.58 · COSMOLOGY", subtitle: "What 95% of the universe's mass-energy budget is — and what we still don't know about it.", readingMinutes: 13, status: "coming-soon", module: "cosmology" },
  // §13 Frontiers — FIG.59–61 (coming-soon)
  { slug: "singularity-theorems", title: "THE PENROSE-HAWKING SINGULARITY THEOREMS", eyebrow: "FIG.59 · FRONTIERS", subtitle: "When does GR predict its own breakdown?", readingMinutes: 12, status: "coming-soon", module: "frontiers" },
  { slug: "the-information-paradox", title: "THE INFORMATION PARADOX", eyebrow: "FIG.60 · FRONTIERS", subtitle: "Hawking radiation says yes, unitarity says no, and the answer is still being argued.", readingMinutes: 13, status: "coming-soon", module: "frontiers" },
  { slug: "what-relativity-doesnt-say", title: "WHAT RELATIVITY DOESN'T SAY", eyebrow: "FIG.61 · FRONTIERS", subtitle: "A century of winning streak, and the wall it has not yet broken through.", readingMinutes: 11, status: "coming-soon", module: "frontiers" },
];

export const BRANCHES: readonly Branch[] = [
  {
    slug: "classical-mechanics",
    index: 1,
    title: "CLASSICAL MECHANICS",
    eyebrow: "§ 01",
    subtitle: "The physics of cannonballs, planets, and pendulums.",
    description:
      "Newton's legacy: forces, motion, and the machinery of the everyday world. Pendulums that keep perfect time, planets that sweep out equal areas, cannonballs that trace parabolas. The math is three hundred years old and still runs the world you live in.",
    modules: CLASSICAL_MECHANICS_MODULES,
    topics: CLASSICAL_MECHANICS_TOPICS,
    status: "live",
  },
  {
    slug: "electromagnetism",
    index: 2,
    title: "ELECTROMAGNETISM",
    eyebrow: "§ 02",
    subtitle: "Light, charge, and the field that holds the world together.",
    description:
      "Maxwell's four equations — the most important four lines in physics — unify electricity, magnetism, and light into a single field theory. Every radio, screen, wire, and star depends on them. The branch ends on the quiet reveal that magnetism was never a second force at all: it is electricity, seen from a moving train.",
    modules: ELECTROMAGNETISM_MODULES,
    topics: ELECTROMAGNETISM_TOPICS,
    status: "live",
  },
  {
    slug: "relativity",
    index: 3,
    title: "RELATIVITY",
    eyebrow: "§ 03",
    subtitle: "The geometry of moving and falling.",
    description:
      "Special relativity erased the line between space and time and made E=mc² a fact about geometry. General relativity erased the line between gravity and curvature and made the universe expand. Together they give the rules light obeys, the rules clocks obey, and the rules black holes do not let escape — the longest-running winning streak in 20th-century physics.",
    modules: RELATIVITY_MODULES,
    topics: RELATIVITY_TOPICS,
    status: "live",
  },
  {
    slug: "thermodynamics",
    index: 4,
    title: "THERMODYNAMICS",
    eyebrow: "§ 04",
    subtitle: "Heat, entropy, and why time moves forward.",
    description:
      "Energy flows one way. Entropy only grows. Out of these two facts come steam engines, refrigerators, the arrow of time, and the heat death of the universe. Thermodynamics is the part of physics that feels most like philosophy.",
    modules: [],
    topics: [],
    status: "coming-soon",
  },
  {
    slug: "quantum",
    index: 5,
    title: "QUANTUM MECHANICS",
    eyebrow: "§ 05",
    subtitle: "The rules the universe actually runs on.",
    description:
      "At small enough scales, the world stops behaving like a world. Particles are waves, measurements disturb reality, and probabilities replace certainties. Every transistor, laser, and MRI machine runs on quantum mechanics.",
    modules: [],
    topics: [],
    status: "coming-soon",
  },
  {
    slug: "modern-physics",
    index: 6,
    title: "MODERN PHYSICS",
    eyebrow: "§ 06",
    subtitle: "From the nucleus to the Standard Model and beyond.",
    description:
      "Where quantum mechanics meets relativity, and where physics meets its open frontier. Particle physics, nuclear physics, cosmology, and the questions we still can't answer about what the universe is made of.",
    modules: [],
    topics: [],
    status: "coming-soon",
  },
];

export function getBranch(slug: string): Branch | undefined {
  return BRANCHES.find((b) => b.slug === slug);
}

export function getTopic(
  branchSlug: string,
  topicSlug: string,
): Topic | undefined {
  const branch = getBranch(branchSlug);
  if (!branch) return undefined;
  return branch.topics.find((t) => t.slug === topicSlug);
}

export function getLiveBranches(): readonly Branch[] {
  return BRANCHES.filter((b) => b.status === "live");
}

export function getAdjacentTopics(
  branchSlug: string,
  topicSlug: string,
): { prev: { branch: Branch; topic: Topic } | null; next: { branch: Branch; topic: Topic } | null } {
  const allLive: { branch: Branch; topic: Topic }[] = [];
  for (const branch of BRANCHES) {
    if (branch.status !== "live") continue;
    for (const topic of branch.topics) {
      if (topic.status !== "live") continue;
      allLive.push({ branch, topic });
    }
  }

  const idx = allLive.findIndex(
    (item) => item.branch.slug === branchSlug && item.topic.slug === topicSlug,
  );
  if (idx === -1) return { prev: null, next: null };

  return {
    prev: idx > 0 ? allLive[idx - 1] : null,
    next: idx < allLive.length - 1 ? allLive[idx + 1] : null,
  };
}

export function getAllRoutes(): string[] {
  const routes: string[] = ["/"];
  for (const branch of BRANCHES) {
    routes.push(`/${branch.slug}`);
    for (const topic of branch.topics) {
      routes.push(`/${branch.slug}/${topic.slug}`);
    }
  }
  routes.push("/physicists");
  for (const physicist of PHYSICISTS) {
    routes.push(`/physicists/${physicist.slug}`);
  }
  routes.push("/dictionary");
  for (const term of GLOSSARY) {
    routes.push(`/dictionary/${term.slug}`);
  }
  return routes;
}
