import type { Problem } from "./types";

/**
 * Structural metadata for every problem on the site.
 *
 * Localised prose (statement, step prompts, hints, common mistakes,
 * walkthrough) lives in messages/<locale>/problems/<branch>/<topic>/<id>.json
 * and is fetched via getProblemStringsForLocale() in lib/problems/strings.ts.
 *
 * Each problem entry must be backed by a vitest-validated solver at
 * `solverPath`. The verifier in lib/problems/verify.ts samples the
 * `canonicalExpr` for each step at random points within `inputDomain`
 * and checks numeric equivalence against the student's expression.
 */
export const PROBLEMS: readonly Problem[] = [
  // ────────────────────────────────────────────────────────────────────
  // module: kinematics-newton
  // ────────────────────────────────────────────────────────────────────

  // motion-in-a-straight-line (5)
  {
    id: "motion-in-a-straight-line-easy-distance-from-velocity-time",
    primaryTopicSlug: "motion-in-a-straight-line",
    relatedTopicSlugs: [],
    difficulty: "easy",
    equationSlugs: ["velocity-time-relation"],
    inputs: { v: { value: 25, units: "m/s" }, t: { value: 8, units: "s" } },
    steps: [
      { id: "d", varName: "d", canonicalExpr: "v * t", units: "m",
        inputDomain: { v: [5, 50], t: [1, 30] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "d",
    solverPath: "lib/problems/classical-mechanics/motion-in-a-straight-line/motion-in-a-straight-line-easy-distance-from-velocity-time.ts",
  },
  {
    id: "motion-in-a-straight-line-medium-final-velocity-from-acceleration",
    primaryTopicSlug: "motion-in-a-straight-line",
    relatedTopicSlugs: [],
    difficulty: "medium",
    equationSlugs: ["velocity-time-relation", "position-time-relation"],
    inputs: { v_0: { value: 5, units: "m/s" }, a: { value: 2, units: "m/s²" }, t: { value: 12, units: "s" } },
    steps: [
      { id: "v_f", varName: "v_f", canonicalExpr: "v_0 + a * t", units: "m/s",
        inputDomain: { v_0: [0, 20], a: [0.5, 5], t: [1, 30] }, toleranceRel: 1e-6 },
      { id: "d", varName: "d", canonicalExpr: "v_0 * t + 0.5 * a * t^2", units: "m",
        inputDomain: { v_0: [0, 20], a: [0.5, 5], t: [1, 30] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "v_f",
    solverPath: "lib/problems/classical-mechanics/motion-in-a-straight-line/motion-in-a-straight-line-medium-final-velocity-from-acceleration.ts",
  },
  {
    id: "motion-in-a-straight-line-hard-stopping-distance-with-reaction-time",
    primaryTopicSlug: "motion-in-a-straight-line",
    relatedTopicSlugs: [],
    difficulty: "hard",
    equationSlugs: ["velocity-time-relation", "position-time-relation", "kinematic-v-squared"],
    inputs: { v_0: { value: 30, units: "m/s" }, t_r: { value: 0.8, units: "s" }, a_brake: { value: 6, units: "m/s²" } },
    steps: [
      { id: "d_react", varName: "d_react", canonicalExpr: "v_0 * t_r", units: "m",
        inputDomain: { v_0: [10, 40], t_r: [0.3, 2] }, toleranceRel: 1e-6 },
      { id: "t_brake", varName: "t_brake", canonicalExpr: "v_0 / a_brake", units: "s",
        inputDomain: { v_0: [10, 40], a_brake: [2, 10] }, toleranceRel: 1e-6 },
      { id: "d_brake", varName: "d_brake", canonicalExpr: "v_0^2 / (2 * a_brake)", units: "m",
        inputDomain: { v_0: [10, 40], a_brake: [2, 10] }, toleranceRel: 1e-6 },
      { id: "d_total", varName: "d_total", canonicalExpr: "v_0 * t_r + v_0^2 / (2 * a_brake)", units: "m",
        inputDomain: { v_0: [10, 40], t_r: [0.3, 2], a_brake: [2, 10] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "d_total",
    solverPath: "lib/problems/classical-mechanics/motion-in-a-straight-line/motion-in-a-straight-line-hard-stopping-distance-with-reaction-time.ts",
  },
  {
    id: "motion-in-a-straight-line-challenge-two-trains-meeting",
    primaryTopicSlug: "motion-in-a-straight-line",
    relatedTopicSlugs: [],
    difficulty: "challenge",
    equationSlugs: ["velocity-time-relation", "relative-velocity-1d"],
    inputs: { v_A: { value: 20, units: "m/s" }, v_B: { value: 10, units: "m/s" }, L: { value: 1200, units: "m" } },
    steps: [
      { id: "closing_speed", varName: "v_close", canonicalExpr: "v_A + v_B", units: "m/s",
        inputDomain: { v_A: [5, 40], v_B: [5, 30] }, toleranceRel: 1e-6 },
      { id: "t_meet", varName: "t_meet", canonicalExpr: "L / (v_A + v_B)", units: "s",
        inputDomain: { v_A: [5, 40], v_B: [5, 30], L: [200, 5000] }, toleranceRel: 1e-6 },
      { id: "x_meet", varName: "x_meet", canonicalExpr: "v_A * L / (v_A + v_B)", units: "m",
        inputDomain: { v_A: [5, 40], v_B: [5, 30], L: [200, 5000] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "x_meet",
    solverPath: "lib/problems/classical-mechanics/motion-in-a-straight-line/motion-in-a-straight-line-challenge-two-trains-meeting.ts",
  },
  {
    id: "motion-in-a-straight-line-exam-overtaking-with-acceleration",
    primaryTopicSlug: "motion-in-a-straight-line",
    relatedTopicSlugs: [],
    difficulty: "exam",
    equationSlugs: ["position-time-relation", "quadratic-formula", "velocity-time-relation"],
    inputs: { d_0: { value: 50, units: "m" }, v_B: { value: 15, units: "m/s" }, a_A: { value: 3, units: "m/s²" } },
    steps: [
      { id: "discriminant", varName: "Delta", canonicalExpr: "v_B^2 + 2 * a_A * d_0", units: "m²/s²",
        inputDomain: { v_B: [5, 30], a_A: [1, 8], d_0: [10, 200] }, toleranceRel: 1e-6 },
      { id: "t_equal", varName: "t_equal", canonicalExpr: "(v_B + sqrt(v_B^2 + 2 * a_A * d_0)) / a_A", units: "s",
        inputDomain: { v_B: [5, 30], a_A: [1, 8], d_0: [10, 200] }, toleranceRel: 1e-6 },
      { id: "x_overtake", varName: "x_overtake", canonicalExpr: "0.5 * a_A * ((v_B + sqrt(v_B^2 + 2 * a_A * d_0)) / a_A)^2", units: "m",
        inputDomain: { v_B: [5, 30], a_A: [1, 8], d_0: [10, 200] }, toleranceRel: 1e-6 },
      { id: "v_A_at_overtake", varName: "v_A_overtake", canonicalExpr: "v_B + sqrt(v_B^2 + 2 * a_A * d_0)", units: "m/s",
        inputDomain: { v_B: [5, 30], a_A: [1, 8], d_0: [10, 200] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "v_A_at_overtake",
    solverPath: "lib/problems/classical-mechanics/motion-in-a-straight-line/motion-in-a-straight-line-exam-overtaking-with-acceleration.ts",
  },

  // vectors-and-projectile-motion (5)
  {
    id: "vectors-and-projectile-motion-easy-range-given-angle-and-speed",
    primaryTopicSlug: "vectors-and-projectile-motion",
    relatedTopicSlugs: [],
    difficulty: "easy",
    equationSlugs: ["velocity-decomposition", "projectile-time-of-flight", "projectile-range"],
    inputs: { v_0: { value: 20, units: "m/s" }, theta: { value: 0.5235987756, units: "rad" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "vx", varName: "v_x", canonicalExpr: "v_0 * cos(theta)", units: "m/s",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4] }, toleranceRel: 1e-6 },
      { id: "vy", varName: "v_y", canonicalExpr: "v_0 * sin(theta)", units: "m/s",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4] }, toleranceRel: 1e-6 },
      { id: "t_flight", varName: "T", canonicalExpr: "2 * v_0 * sin(theta) / g", units: "s",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "R", varName: "R", canonicalExpr: "v_0^2 * sin(2*theta) / g", units: "m",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4], g: [9, 10] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "R",
    solverPath: "lib/problems/classical-mechanics/vectors-and-projectile-motion/vectors-and-projectile-motion-easy-range-given-angle-and-speed.ts",
  },
  {
    id: "vectors-and-projectile-motion-medium-peak-height-and-time",
    primaryTopicSlug: "vectors-and-projectile-motion",
    relatedTopicSlugs: [],
    difficulty: "medium",
    equationSlugs: ["velocity-decomposition", "projectile-peak-height", "projectile-time-of-flight"],
    inputs: { v_0: { value: 35, units: "m/s" }, theta: { value: 0.8726646259, units: "rad" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "vy", varName: "v_y", canonicalExpr: "v_0 * sin(theta)", units: "m/s",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4] }, toleranceRel: 1e-6 },
      { id: "t_peak", varName: "t_H", canonicalExpr: "v_0 * sin(theta) / g", units: "s",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "H", varName: "H", canonicalExpr: "v_0^2 * sin(theta)^2 / (2 * g)", units: "m",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4], g: [9, 10] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "H",
    solverPath: "lib/problems/classical-mechanics/vectors-and-projectile-motion/vectors-and-projectile-motion-medium-peak-height-and-time.ts",
  },
  {
    id: "vectors-and-projectile-motion-hard-velocity-at-given-time",
    primaryTopicSlug: "vectors-and-projectile-motion",
    relatedTopicSlugs: [],
    difficulty: "hard",
    equationSlugs: ["velocity-decomposition", "kinematic-equations"],
    inputs: { v_0: { value: 40, units: "m/s" }, theta: { value: 1.0471975512, units: "rad" }, t: { value: 2, units: "s" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "vx", varName: "v_x", canonicalExpr: "v_0 * cos(theta)", units: "m/s",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4] }, toleranceRel: 1e-6 },
      { id: "vy_t", varName: "v_y_t", canonicalExpr: "v_0 * sin(theta) - g * t", units: "m/s",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4], t: [0.5, 3], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "speed_t", varName: "speed", canonicalExpr: "sqrt((v_0 * cos(theta))^2 + (v_0 * sin(theta) - g * t)^2)", units: "m/s",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4], t: [0.5, 3], g: [9, 10] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "speed_t",
    solverPath: "lib/problems/classical-mechanics/vectors-and-projectile-motion/vectors-and-projectile-motion-hard-velocity-at-given-time.ts",
  },
  {
    id: "vectors-and-projectile-motion-challenge-complementary-angles-same-range",
    primaryTopicSlug: "vectors-and-projectile-motion",
    relatedTopicSlugs: [],
    difficulty: "challenge",
    equationSlugs: ["projectile-range", "projectile-time-of-flight", "complementary-angles"],
    inputs: { v_0: { value: 50, units: "m/s" }, R_target: { value: 200, units: "m" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "sin2theta", varName: "sin2theta", canonicalExpr: "R_target * g / v_0^2", units: "",
        inputDomain: { R_target: [100, 240], v_0: [40, 60], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "theta_low", varName: "theta_low", canonicalExpr: "asin(R_target * g / v_0^2) / 2", units: "rad",
        inputDomain: { R_target: [100, 240], v_0: [40, 60], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "theta_high", varName: "theta_high", canonicalExpr: "PI/2 - asin(R_target * g / v_0^2) / 2", units: "rad",
        inputDomain: { R_target: [100, 240], v_0: [40, 60], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "delta_T", varName: "delta_T",
        canonicalExpr: "2 * v_0 * sin(PI/2 - asin(R_target * g / v_0^2) / 2) / g - 2 * v_0 * sin(asin(R_target * g / v_0^2) / 2) / g",
        units: "s", inputDomain: { R_target: [100, 240], v_0: [40, 60], g: [9, 10] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "delta_T",
    solverPath: "lib/problems/classical-mechanics/vectors-and-projectile-motion/vectors-and-projectile-motion-challenge-complementary-angles-same-range.ts",
  },
  {
    id: "vectors-and-projectile-motion-exam-position-and-speed-mid-flight",
    primaryTopicSlug: "vectors-and-projectile-motion",
    relatedTopicSlugs: [],
    difficulty: "exam",
    equationSlugs: ["velocity-decomposition", "projectile-time-of-flight", "projectile-peak-height", "kinematic-equations"],
    inputs: { v_0: { value: 45, units: "m/s" }, theta: { value: 0.6457718232, units: "rad" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "vx", varName: "v_x", canonicalExpr: "v_0 * cos(theta)", units: "m/s",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4] }, toleranceRel: 1e-6 },
      { id: "T", varName: "T", canonicalExpr: "2 * v_0 * sin(theta) / g", units: "s",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "x_mid", varName: "x_mid", canonicalExpr: "v_0 * cos(theta) * v_0 * sin(theta) / g", units: "m",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "y_mid", varName: "y_mid", canonicalExpr: "v_0^2 * sin(theta)^2 / (2 * g)", units: "m",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "speed_mid", varName: "speed_mid", canonicalExpr: "v_0 * cos(theta)", units: "m/s",
        inputDomain: { v_0: [10, 50], theta: [0.1, 1.4] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "speed_mid",
    solverPath: "lib/problems/classical-mechanics/vectors-and-projectile-motion/vectors-and-projectile-motion-exam-position-and-speed-mid-flight.ts",
  },

  // newtons-three-laws (5)
  {
    id: "newtons-three-laws-easy-acceleration-from-net-force",
    primaryTopicSlug: "newtons-three-laws",
    relatedTopicSlugs: [],
    difficulty: "easy",
    equationSlugs: ["newtons-second-law"],
    inputs: { F_net: { value: 30, units: "N" }, m: { value: 5, units: "kg" } },
    steps: [
      { id: "a", varName: "a", canonicalExpr: "F_net / m", units: "m/s²",
        inputDomain: { F_net: [10, 500], m: [0.5, 50] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "a",
    solverPath: "lib/problems/classical-mechanics/newtons-three-laws/newtons-three-laws-easy-acceleration-from-net-force.ts",
  },
  {
    id: "newtons-three-laws-medium-friction-on-flat-surface",
    primaryTopicSlug: "newtons-three-laws",
    relatedTopicSlugs: ["friction-and-drag"],
    difficulty: "medium",
    equationSlugs: ["newtons-second-law", "weight-equation", "friction-force", "net-force-summation"],
    inputs: { m: { value: 12, units: "kg" }, F_applied: { value: 80, units: "N" }, mu_k: { value: 0.35, units: "" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "F_normal", varName: "F_N", canonicalExpr: "m * g", units: "N",
        inputDomain: { m: [1, 100], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "F_friction", varName: "F_friction", canonicalExpr: "mu_k * m * g", units: "N",
        inputDomain: { mu_k: [0.1, 0.8], m: [1, 100], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "F_net", varName: "F_net", canonicalExpr: "F_applied - mu_k * m * g", units: "N",
        inputDomain: { F_applied: [10, 500], mu_k: [0.1, 0.8], m: [1, 100], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "a", varName: "a", canonicalExpr: "(F_applied - mu_k * m * g) / m", units: "m/s²",
        inputDomain: { F_applied: [10, 500], mu_k: [0.1, 0.8], m: [1, 100], g: [9, 10] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "a",
    solverPath: "lib/problems/classical-mechanics/newtons-three-laws/newtons-three-laws-medium-friction-on-flat-surface.ts",
  },
  {
    id: "newtons-three-laws-hard-elevator-apparent-weight",
    primaryTopicSlug: "newtons-three-laws",
    relatedTopicSlugs: [],
    difficulty: "hard",
    equationSlugs: ["newtons-second-law", "weight-equation", "net-force-summation"],
    inputs: { m: { value: 70, units: "kg" }, a_elevator: { value: 2.5, units: "m/s²" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "W", varName: "W", canonicalExpr: "m * g", units: "N",
        inputDomain: { m: [10, 200], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "F_net", varName: "F_net", canonicalExpr: "m * a_elevator", units: "N",
        inputDomain: { m: [10, 200], a_elevator: [0.1, 15] }, toleranceRel: 1e-6 },
      { id: "N", varName: "N", canonicalExpr: "m * g + m * a_elevator", units: "N",
        inputDomain: { m: [10, 200], g: [9, 10], a_elevator: [0.1, 15] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "N",
    solverPath: "lib/problems/classical-mechanics/newtons-three-laws/newtons-three-laws-hard-elevator-apparent-weight.ts",
  },
  {
    id: "newtons-three-laws-challenge-atwood-machine",
    primaryTopicSlug: "newtons-three-laws",
    relatedTopicSlugs: [],
    difficulty: "challenge",
    equationSlugs: ["newtons-second-law", "weight-equation", "net-force-summation", "newtons-third-law"],
    inputs: { m_1: { value: 4, units: "kg" }, m_2: { value: 6, units: "kg" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "F_net_system", varName: "F_net", canonicalExpr: "(m_2 - m_1) * g", units: "N",
        inputDomain: { m_1: [0.5, 20], m_2: [1, 30], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "m_total", varName: "m_total", canonicalExpr: "m_1 + m_2", units: "kg",
        inputDomain: { m_1: [0.5, 20], m_2: [1, 30] }, toleranceRel: 1e-6 },
      { id: "a", varName: "a", canonicalExpr: "(m_2 - m_1) * g / (m_1 + m_2)", units: "m/s²",
        inputDomain: { m_1: [0.5, 20], m_2: [1, 30], g: [9, 10] }, toleranceRel: 1e-6 },
      { id: "T", varName: "T", canonicalExpr: "m_1 * (g + (m_2 - m_1) * g / (m_1 + m_2))", units: "N",
        inputDomain: { m_1: [0.5, 20], m_2: [1, 30], g: [9, 10] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "T",
    solverPath: "lib/problems/classical-mechanics/newtons-three-laws/newtons-three-laws-challenge-atwood-machine.ts",
  },
  {
    id: "newtons-three-laws-exam-block-on-incline-with-friction",
    primaryTopicSlug: "newtons-three-laws",
    relatedTopicSlugs: ["friction-and-drag"],
    difficulty: "exam",
    equationSlugs: ["newtons-second-law", "weight-equation", "friction-force", "net-force-summation"],
    inputs: { m: { value: 15, units: "kg" }, theta_deg: { value: 35, units: "°" }, mu_k: { value: 0.2, units: "" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "theta_rad", varName: "theta_rad", canonicalExpr: "theta_deg * PI / 180", units: "rad",
        inputDomain: { theta_deg: [5, 80] }, toleranceRel: 1e-6 },
      { id: "F_gravity_parallel", varName: "F_g_parallel", canonicalExpr: "m * g * sin(theta_deg * PI / 180)", units: "N",
        inputDomain: { m: [1, 100], g: [9, 10], theta_deg: [5, 80] }, toleranceRel: 1e-6 },
      { id: "F_normal", varName: "F_N", canonicalExpr: "m * g * cos(theta_deg * PI / 180)", units: "N",
        inputDomain: { m: [1, 100], g: [9, 10], theta_deg: [5, 80] }, toleranceRel: 1e-6 },
      { id: "F_friction", varName: "F_friction", canonicalExpr: "mu_k * m * g * cos(theta_deg * PI / 180)", units: "N",
        inputDomain: { mu_k: [0.05, 0.8], m: [1, 100], g: [9, 10], theta_deg: [5, 80] }, toleranceRel: 1e-6 },
      { id: "a", varName: "a", canonicalExpr: "g * (sin(theta_deg * PI / 180) - mu_k * cos(theta_deg * PI / 180))", units: "m/s²",
        inputDomain: { mu_k: [0.05, 0.8], g: [9, 10], theta_deg: [5, 80] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "a",
    solverPath: "lib/problems/classical-mechanics/newtons-three-laws/newtons-three-laws-exam-block-on-incline-with-friction.ts",
  },

  // friction-and-drag (5)
  {
    id: "friction-and-drag-easy-friction-force-on-flat-surface",
    primaryTopicSlug: "friction-and-drag",
    relatedTopicSlugs: [],
    difficulty: "easy",
    equationSlugs: ["friction-force", "kinetic-friction"],
    inputs: { m: { value: 8, units: "kg" }, mu_k: { value: 0.4, units: "" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "F_N", varName: "F_N", canonicalExpr: "m * g", units: "N",
        inputDomain: { m: [0.5, 20], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "F_friction", varName: "F_friction", canonicalExpr: "mu_k * m * g", units: "N",
        inputDomain: { mu_k: [0.1, 0.8], m: [0.5, 20], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "F_friction",
    solverPath: "lib/problems/classical-mechanics/friction-and-drag/friction-and-drag-easy-friction-force-on-flat-surface.ts",
  },
  {
    id: "friction-and-drag-medium-acceleration-on-rough-ramp",
    primaryTopicSlug: "friction-and-drag",
    relatedTopicSlugs: [],
    difficulty: "medium",
    equationSlugs: ["kinetic-friction", "friction-force"],
    inputs: { m: { value: 5, units: "kg" }, theta: { value: 0.5236, units: "rad" }, mu_k: { value: 0.25, units: "" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "F_N", varName: "F_N", canonicalExpr: "m * g * cos(theta)", units: "N",
        inputDomain: { m: [0.5, 20], g: [9.8, 9.8], theta: [0.1, 1.3] }, toleranceRel: 1e-6 },
      { id: "F_friction", varName: "F_friction", canonicalExpr: "mu_k * m * g * cos(theta)", units: "N",
        inputDomain: { mu_k: [0.1, 0.8], m: [0.5, 20], g: [9.8, 9.8], theta: [0.1, 1.3] }, toleranceRel: 1e-6 },
      { id: "F_net", varName: "F_net", canonicalExpr: "m * g * sin(theta) - mu_k * m * g * cos(theta)", units: "N",
        inputDomain: { mu_k: [0.1, 0.8], m: [0.5, 20], g: [9.8, 9.8], theta: [0.1, 1.3] }, toleranceRel: 1e-6 },
      { id: "a", varName: "a", canonicalExpr: "g * (sin(theta) - mu_k * cos(theta))", units: "m/s²",
        inputDomain: { mu_k: [0.1, 0.8], g: [9.8, 9.8], theta: [0.1, 1.3] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "a",
    solverPath: "lib/problems/classical-mechanics/friction-and-drag/friction-and-drag-medium-acceleration-on-rough-ramp.ts",
  },
  {
    id: "friction-and-drag-hard-terminal-velocity-stokes-sphere",
    primaryTopicSlug: "friction-and-drag",
    relatedTopicSlugs: [],
    difficulty: "hard",
    equationSlugs: ["drag-force-linear", "terminal-velocity"],
    inputs: { r: { value: 0.003, units: "m" }, eta: { value: 0.001, units: "Pa·s" }, m: { value: 1.5e-4, units: "kg" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "b", varName: "b", canonicalExpr: "6 * PI * eta * r", units: "kg/s",
        inputDomain: { eta: [1e-4, 1e-2], r: [1e-4, 0.01] }, toleranceRel: 1e-6 },
      { id: "v_t", varName: "v_t", canonicalExpr: "m * g / (6 * PI * eta * r)", units: "m/s",
        inputDomain: { m: [1e-5, 1e-3], g: [9.8, 9.8], eta: [1e-4, 1e-2], r: [1e-4, 0.01] }, toleranceRel: 1e-6 },
      { id: "tau", varName: "tau", canonicalExpr: "m / (6 * PI * eta * r)", units: "s",
        inputDomain: { m: [1e-5, 1e-3], eta: [1e-4, 1e-2], r: [1e-4, 0.01] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "v_t",
    solverPath: "lib/problems/classical-mechanics/friction-and-drag/friction-and-drag-hard-terminal-velocity-stokes-sphere.ts",
  },
  {
    id: "friction-and-drag-challenge-stopping-distance-on-rough-floor",
    primaryTopicSlug: "friction-and-drag",
    relatedTopicSlugs: [],
    difficulty: "challenge",
    equationSlugs: ["kinetic-friction", "friction-force"],
    inputs: { v_0: { value: 20, units: "m/s" }, mu_k: { value: 0.5, units: "" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "a_decel", varName: "a_decel", canonicalExpr: "mu_k * g", units: "m/s²",
        inputDomain: { mu_k: [0.1, 0.8], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "t_stop", varName: "t_stop", canonicalExpr: "v_0 / (mu_k * g)", units: "s",
        inputDomain: { v_0: [5, 40], mu_k: [0.1, 0.8], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "d_stop", varName: "d_stop", canonicalExpr: "v_0^2 / (2 * mu_k * g)", units: "m",
        inputDomain: { v_0: [5, 40], mu_k: [0.1, 0.8], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "d_stop",
    solverPath: "lib/problems/classical-mechanics/friction-and-drag/friction-and-drag-challenge-stopping-distance-on-rough-floor.ts",
  },
  {
    id: "friction-and-drag-exam-terminal-velocity-quadratic-drag",
    primaryTopicSlug: "friction-and-drag",
    relatedTopicSlugs: [],
    difficulty: "exam",
    equationSlugs: ["drag-force-quadratic", "terminal-velocity"],
    inputs: { m: { value: 75, units: "kg" }, rho: { value: 1.225, units: "kg/m³" }, C_d: { value: 1.0, units: "" }, A: { value: 0.7, units: "m²" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "k", varName: "k", canonicalExpr: "rho * C_d * A / 2", units: "kg/m",
        inputDomain: { rho: [1.0, 1.4], C_d: [0.5, 2.0], A: [0.3, 1.5] }, toleranceRel: 1e-6 },
      { id: "F_grav", varName: "F_grav", canonicalExpr: "m * g", units: "N",
        inputDomain: { m: [50, 120], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "v_t", varName: "v_t", canonicalExpr: "sqrt(2 * m * g / (rho * C_d * A))", units: "m/s",
        inputDomain: { m: [50, 120], g: [9.8, 9.8], rho: [1.0, 1.4], C_d: [0.5, 2.0], A: [0.3, 1.5] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "v_t",
    solverPath: "lib/problems/classical-mechanics/friction-and-drag/friction-and-drag-exam-terminal-velocity-quadratic-drag.ts",
  },

  // ────────────────────────────────────────────────────────────────────
  // module: oscillations
  // ────────────────────────────────────────────────────────────────────

  // the-simple-pendulum (5) — reconstructed from solver files
  {
    id: "the-simple-pendulum-easy-period-from-length",
    primaryTopicSlug: "the-simple-pendulum",
    relatedTopicSlugs: [],
    difficulty: "easy",
    equationSlugs: ["small-angle-pendulum-period", "pendulum-frequency"],
    inputs: { L: { value: 1.2, units: "m" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "omega", varName: "omega", canonicalExpr: "sqrt(g / L)", units: "rad/s",
        inputDomain: { L: [0.1, 5], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "T", varName: "T", canonicalExpr: "2 * PI * sqrt(L / g)", units: "s",
        inputDomain: { L: [0.1, 5], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "T",
    solverPath: "lib/problems/classical-mechanics/the-simple-pendulum/the-simple-pendulum-easy-period-from-length.ts",
  },
  {
    id: "the-simple-pendulum-medium-length-from-period",
    primaryTopicSlug: "the-simple-pendulum",
    relatedTopicSlugs: [],
    difficulty: "medium",
    equationSlugs: ["small-angle-pendulum-period"],
    inputs: { T: { value: 3.0, units: "s" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "tau", varName: "tau", canonicalExpr: "T / (2 * PI)", units: "s/rad",
        inputDomain: { T: [1, 5] }, toleranceRel: 1e-6 },
      { id: "L", varName: "L", canonicalExpr: "g * (T / (2 * PI))^2", units: "m",
        inputDomain: { T: [1, 5], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "L",
    solverPath: "lib/problems/classical-mechanics/the-simple-pendulum/the-simple-pendulum-medium-length-from-period.ts",
  },
  {
    id: "the-simple-pendulum-hard-energy-amplitude-relation",
    primaryTopicSlug: "the-simple-pendulum",
    relatedTopicSlugs: [],
    difficulty: "hard",
    equationSlugs: ["pendulum-energy-conservation", "small-angle-pendulum-period"],
    inputs: { m: { value: 0.5, units: "kg" }, L: { value: 0.8, units: "m" }, g: { value: 9.80665, units: "m/s²" }, theta_0: { value: 0.15, units: "rad" } },
    steps: [
      { id: "h", varName: "h", canonicalExpr: "L * (1 - cos(theta_0))", units: "m",
        inputDomain: { L: [0.1, 5], theta_0: [0.05, 0.3] }, toleranceRel: 1e-6 },
      { id: "PE_max", varName: "PE_max", canonicalExpr: "m * g * L * (1 - cos(theta_0))", units: "J",
        inputDomain: { m: [0.1, 5], g: [9.8, 9.8], L: [0.1, 5], theta_0: [0.05, 0.3] }, toleranceRel: 1e-6 },
      { id: "v_max", varName: "v_max", canonicalExpr: "sqrt(2 * g * L * (1 - cos(theta_0)))", units: "m/s",
        inputDomain: { g: [9.8, 9.8], L: [0.1, 5], theta_0: [0.05, 0.3] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "v_max",
    solverPath: "lib/problems/classical-mechanics/the-simple-pendulum/the-simple-pendulum-hard-energy-amplitude-relation.ts",
  },
  {
    id: "the-simple-pendulum-challenge-large-angle-period-correction",
    primaryTopicSlug: "the-simple-pendulum",
    relatedTopicSlugs: ["beyond-small-angles"],
    difficulty: "challenge",
    equationSlugs: ["small-angle-pendulum-period", "small-angle-period-correction"],
    inputs: { L: { value: 1.0, units: "m" }, g: { value: 9.80665, units: "m/s²" }, theta_0: { value: 0.6, units: "rad" } },
    steps: [
      { id: "T_small", varName: "T_small", canonicalExpr: "2 * PI * sqrt(L / g)", units: "s",
        inputDomain: { L: [0.1, 5], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "k", varName: "k", canonicalExpr: "sin(theta_0 / 2)", units: "",
        inputDomain: { theta_0: [0.3, 1.4] }, toleranceRel: 1e-6 },
      { id: "T_exact", varName: "T_exact",
        canonicalExpr: "(2 * PI * sqrt(L / g)) * (1 + theta_0^2 / 16 + 11 * theta_0^4 / 3072)",
        units: "s", inputDomain: { L: [0.1, 5], g: [9.8, 9.8], theta_0: [0.3, 1.4] }, toleranceRel: 1e-3 },
      { id: "delta", varName: "delta",
        canonicalExpr: "theta_0^2 / 16 + 11 * theta_0^4 / 3072",
        units: "", inputDomain: { theta_0: [0.3, 1.4] }, toleranceRel: 1e-3 },
    ],
    finalAnswerStepId: "T_exact",
    solverPath: "lib/problems/classical-mechanics/the-simple-pendulum/the-simple-pendulum-challenge-large-angle-period-correction.ts",
  },
  {
    id: "the-simple-pendulum-exam-gravity-from-two-pendulums",
    primaryTopicSlug: "the-simple-pendulum",
    relatedTopicSlugs: [],
    difficulty: "exam",
    equationSlugs: ["small-angle-pendulum-period", "pendulum-frequency"],
    inputs: { L_1: { value: 0.5, units: "m" }, T_1: { value: 1.4187, units: "s" }, L_2: { value: 2.0, units: "m" }, T_2: { value: 2.8375, units: "s" } },
    steps: [
      { id: "g_1", varName: "g_1", canonicalExpr: "L_1 * (2 * PI / T_1)^2", units: "m/s²",
        inputDomain: { L_1: [0.1, 5], T_1: [0.5, 5] }, toleranceRel: 1e-6 },
      { id: "g_2", varName: "g_2", canonicalExpr: "L_2 * (2 * PI / T_2)^2", units: "m/s²",
        inputDomain: { L_2: [0.1, 5], T_2: [0.5, 5] }, toleranceRel: 1e-6 },
      { id: "g_avg", varName: "g_avg",
        canonicalExpr: "(L_1 * (2 * PI / T_1)^2 + L_2 * (2 * PI / T_2)^2) / 2",
        units: "m/s²", inputDomain: { L_1: [0.1, 5], T_1: [0.5, 5], L_2: [0.1, 5], T_2: [0.5, 5] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "g_avg",
    solverPath: "lib/problems/classical-mechanics/the-simple-pendulum/the-simple-pendulum-exam-gravity-from-two-pendulums.ts",
  },

  // beyond-small-angles (5) — clean from agent
  {
    id: "beyond-small-angles-easy-percent-error-at-30-degrees",
    primaryTopicSlug: "beyond-small-angles",
    relatedTopicSlugs: ["the-simple-pendulum"],
    difficulty: "easy",
    equationSlugs: ["large-angle-pendulum-period", "small-angle-period-correction"],
    inputs: { theta_0: { value: 0.5235987755982988, units: "rad" }, L: { value: 1.0, units: "m" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "T_small", varName: "T_small", canonicalExpr: "2 * PI * sqrt(L / g)", units: "s",
        inputDomain: { L: [0.1, 5], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "T_exact", varName: "T_exact",
        canonicalExpr: "(2 * PI * sqrt(L / g)) * (1 + theta_0^2 / 16 + 11 * theta_0^4 / 3072)",
        units: "s", inputDomain: { L: [0.1, 5], theta_0: [0.3, 1.4], g: [9.8, 9.8] }, toleranceRel: 1e-4 },
      { id: "pct_err", varName: "pct_err",
        canonicalExpr: "(theta_0^2 / 16 + 11 * theta_0^4 / 3072) / (1 + theta_0^2 / 16 + 11 * theta_0^4 / 3072) * 100",
        units: "%", inputDomain: { theta_0: [0.3, 1.4] }, toleranceRel: 1e-4 },
    ],
    finalAnswerStepId: "pct_err",
    solverPath: "lib/problems/classical-mechanics/beyond-small-angles/beyond-small-angles-easy-percent-error-at-30-degrees.ts",
  },
  {
    id: "beyond-small-angles-medium-first-order-period-correction",
    primaryTopicSlug: "beyond-small-angles",
    relatedTopicSlugs: ["the-simple-pendulum"],
    difficulty: "medium",
    equationSlugs: ["small-angle-period-correction", "taylor-expansion-period"],
    inputs: { theta_0: { value: 0.8, units: "rad" }, L: { value: 1.5, units: "m" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "T_small", varName: "T_small", canonicalExpr: "2 * PI * sqrt(L / g)", units: "s",
        inputDomain: { L: [0.1, 5], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "delta_T", varName: "delta_T", canonicalExpr: "(2 * PI * sqrt(L / g)) * theta_0^2 / 16", units: "s",
        inputDomain: { L: [0.1, 5], theta_0: [0.3, 1.4], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "T_corr", varName: "T_corr", canonicalExpr: "(2 * PI * sqrt(L / g)) * (1 + theta_0^2 / 16)", units: "s",
        inputDomain: { L: [0.1, 5], theta_0: [0.3, 1.4], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "T_series", varName: "T_series",
        canonicalExpr: "(2 * PI * sqrt(L / g)) * (1 + theta_0^2 / 16 + 11 * theta_0^4 / 3072)",
        units: "s", inputDomain: { L: [0.1, 5], theta_0: [0.3, 1.4], g: [9.8, 9.8] }, toleranceRel: 1e-4 },
    ],
    finalAnswerStepId: "T_series",
    solverPath: "lib/problems/classical-mechanics/beyond-small-angles/beyond-small-angles-medium-first-order-period-correction.ts",
  },
  {
    id: "beyond-small-angles-hard-large-angle-period-from-elliptic-integral",
    primaryTopicSlug: "beyond-small-angles",
    relatedTopicSlugs: ["the-simple-pendulum"],
    difficulty: "hard",
    equationSlugs: ["large-angle-pendulum-period", "complete-elliptic-integral"],
    inputs: { theta_0: { value: 1.2, units: "rad" }, L: { value: 2.0, units: "m" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "k", varName: "k", canonicalExpr: "sin(theta_0 / 2)", units: "",
        inputDomain: { theta_0: [0.3, 1.4] }, toleranceRel: 1e-6 },
      { id: "T_small", varName: "T_small", canonicalExpr: "2 * PI * sqrt(L / g)", units: "s",
        inputDomain: { L: [0.1, 5], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "T_exact", varName: "T_exact",
        canonicalExpr: "(2 * PI * sqrt(L / g)) * (1 + theta_0^2 / 16 + 11 * theta_0^4 / 3072)",
        units: "s", inputDomain: { L: [0.1, 5], theta_0: [0.3, 1.4], g: [9.8, 9.8] }, toleranceRel: 1e-3 },
    ],
    finalAnswerStepId: "T_exact",
    solverPath: "lib/problems/classical-mechanics/beyond-small-angles/beyond-small-angles-hard-large-angle-period-from-elliptic-integral.ts",
  },
  {
    id: "beyond-small-angles-challenge-length-from-large-angle-period",
    primaryTopicSlug: "beyond-small-angles",
    relatedTopicSlugs: ["the-simple-pendulum"],
    difficulty: "challenge",
    equationSlugs: ["large-angle-pendulum-period", "complete-elliptic-integral"],
    inputs: { T: { value: 3.0, units: "s" }, theta_0: { value: 1.0, units: "rad" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "k", varName: "k", canonicalExpr: "sin(theta_0 / 2)", units: "",
        inputDomain: { theta_0: [0.3, 1.4] }, toleranceRel: 1e-6 },
      { id: "K_val", varName: "K", canonicalExpr: "(PI / 2) * (1 + sin(theta_0 / 2)^2 / 4 + 9 * sin(theta_0 / 2)^4 / 64)",
        units: "", inputDomain: { theta_0: [0.3, 1.4] }, toleranceRel: 5e-4 },
      { id: "L", varName: "L",
        canonicalExpr: "g * (T / (4 * (PI / 2) * (1 + sin(theta_0 / 2)^2 / 4 + 9 * sin(theta_0 / 2)^4 / 64)))^2",
        units: "m", inputDomain: { T: [1, 5], theta_0: [0.3, 1.4], g: [9.8, 9.8] }, toleranceRel: 5e-4 },
    ],
    finalAnswerStepId: "L",
    solverPath: "lib/problems/classical-mechanics/beyond-small-angles/beyond-small-angles-challenge-length-from-large-angle-period.ts",
  },
  {
    id: "beyond-small-angles-exam-amplitude-dependence-of-period",
    primaryTopicSlug: "beyond-small-angles",
    relatedTopicSlugs: ["the-simple-pendulum"],
    difficulty: "exam",
    equationSlugs: ["large-angle-pendulum-period", "complete-elliptic-integral", "small-angle-period-correction"],
    inputs: { theta_0: { value: 1.4, units: "rad" }, L: { value: 1.0, units: "m" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "T_small", varName: "T_small", canonicalExpr: "2 * PI * sqrt(L / g)", units: "s",
        inputDomain: { L: [0.1, 5], g: [9.8, 9.8] }, toleranceRel: 1e-6 },
      { id: "T_exact", varName: "T_exact",
        canonicalExpr: "(2 * PI * sqrt(L / g)) * (1 + theta_0^2 / 16 + 11 * theta_0^4 / 3072)",
        units: "s", inputDomain: { L: [0.1, 5], theta_0: [0.3, 1.4], g: [9.8, 9.8] }, toleranceRel: 5e-3 },
      { id: "pct_stretch", varName: "pct_stretch",
        canonicalExpr: "(theta_0^2 / 16 + 11 * theta_0^4 / 3072) * 100",
        units: "%", inputDomain: { theta_0: [0.3, 1.4] }, toleranceRel: 5e-3 },
      { id: "n_cycles", varName: "n_cycles",
        canonicalExpr: "1 / (theta_0^2 / 16 + 11 * theta_0^4 / 3072)",
        units: "", inputDomain: { theta_0: [0.3, 1.4] }, toleranceRel: 5e-3 },
    ],
    finalAnswerStepId: "n_cycles",
    solverPath: "lib/problems/classical-mechanics/beyond-small-angles/beyond-small-angles-exam-amplitude-dependence-of-period.ts",
  },

  // oscillators-everywhere (5) — schema fixes applied
  {
    id: "oscillators-everywhere-easy-spring-period-from-mass",
    primaryTopicSlug: "oscillators-everywhere",
    relatedTopicSlugs: [],
    difficulty: "easy",
    equationSlugs: ["simple-harmonic-motion", "spring-frequency"],
    inputs: { k: { value: 200, units: "N/m" }, m: { value: 0.5, units: "kg" } },
    steps: [
      { id: "omega", varName: "omega", canonicalExpr: "sqrt(k / m)", units: "rad/s",
        inputDomain: { k: [10, 500], m: [0.1, 5] }, toleranceRel: 1e-6 },
      { id: "T", varName: "T", canonicalExpr: "2 * PI / sqrt(k / m)", units: "s",
        inputDomain: { k: [10, 500], m: [0.1, 5] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "T",
    solverPath: "lib/problems/classical-mechanics/oscillators-everywhere/oscillators-everywhere-easy-spring-period-from-mass.ts",
  },
  {
    id: "oscillators-everywhere-medium-energy-of-shm",
    primaryTopicSlug: "oscillators-everywhere",
    relatedTopicSlugs: [],
    difficulty: "medium",
    equationSlugs: ["shm-energy", "simple-harmonic-motion", "spring-frequency"],
    inputs: { k: { value: 80, units: "N/m" }, A: { value: 0.15, units: "m" }, m: { value: 2.0, units: "kg" } },
    steps: [
      { id: "E", varName: "E", canonicalExpr: "0.5 * k * A^2", units: "J",
        inputDomain: { k: [10, 500], A: [0.01, 0.5] }, toleranceRel: 1e-6 },
      { id: "v_max", varName: "v_max", canonicalExpr: "A * sqrt(k / m)", units: "m/s",
        inputDomain: { k: [10, 500], A: [0.01, 0.5], m: [0.1, 5] }, toleranceRel: 1e-6 },
      { id: "omega", varName: "omega", canonicalExpr: "sqrt(k / m)", units: "rad/s",
        inputDomain: { k: [10, 500], m: [0.1, 5] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "E",
    solverPath: "lib/problems/classical-mechanics/oscillators-everywhere/oscillators-everywhere-medium-energy-of-shm.ts",
  },
  {
    id: "oscillators-everywhere-hard-damped-free-displacement",
    primaryTopicSlug: "oscillators-everywhere",
    relatedTopicSlugs: ["damped-and-driven-oscillations"],
    difficulty: "hard",
    equationSlugs: ["simple-harmonic-motion", "shm-position"],
    inputs: { k: { value: 25, units: "N/m" }, m: { value: 1, units: "kg" }, b: { value: 2, units: "N·s/m" }, x0: { value: 0.3, units: "m" }, t: { value: 1.5, units: "s" } },
    steps: [
      { id: "omega0", varName: "omega_0", canonicalExpr: "sqrt(k / m)", units: "rad/s",
        inputDomain: { k: [10, 500], m: [0.1, 5] }, toleranceRel: 1e-6 },
      { id: "gamma", varName: "gamma", canonicalExpr: "b / m", units: "s^-1",
        inputDomain: { b: [0.5, 5], m: [0.1, 5] }, toleranceRel: 1e-6 },
      { id: "omegaD", varName: "omega_d", canonicalExpr: "sqrt(k / m - b^2 / (4 * m^2))", units: "rad/s",
        inputDomain: { k: [10, 500], m: [0.1, 5], b: [0.5, 5] }, toleranceRel: 1e-6 },
      { id: "tau", varName: "tau", canonicalExpr: "2 * m / b", units: "s",
        inputDomain: { m: [0.1, 5], b: [0.5, 5] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "omegaD",
    solverPath: "lib/problems/classical-mechanics/oscillators-everywhere/oscillators-everywhere-hard-damped-free-displacement.ts",
  },
  {
    id: "oscillators-everywhere-challenge-coupled-pendulum-normal-modes",
    primaryTopicSlug: "oscillators-everywhere",
    relatedTopicSlugs: [],
    difficulty: "challenge",
    equationSlugs: ["simple-harmonic-motion", "coupled-normal-modes"],
    inputs: { L: { value: 0.5, units: "m" }, k_c: { value: 0.8, units: "N/m" }, m: { value: 0.25, units: "kg" }, g: { value: 9.80665, units: "m/s²" } },
    steps: [
      { id: "omega0", varName: "omega_0", canonicalExpr: "sqrt(g / L)", units: "rad/s",
        inputDomain: { g: [9.8, 9.8], L: [0.1, 5] }, toleranceRel: 1e-6 },
      { id: "omega1", varName: "omega_1", canonicalExpr: "sqrt(g / L)", units: "rad/s",
        inputDomain: { g: [9.8, 9.8], L: [0.1, 5] }, toleranceRel: 1e-6 },
      { id: "omega2", varName: "omega_2", canonicalExpr: "sqrt(g / L + 2 * k_c / m)", units: "rad/s",
        inputDomain: { g: [9.8, 9.8], L: [0.1, 5], k_c: [0.1, 5], m: [0.05, 2] }, toleranceRel: 1e-6 },
      { id: "T_beat", varName: "T_beat",
        canonicalExpr: "2 * PI / (sqrt(g / L + 2 * k_c / m) - sqrt(g / L))",
        units: "s", inputDomain: { g: [9.8, 9.8], L: [0.1, 5], k_c: [0.1, 5], m: [0.05, 2] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "omega2",
    solverPath: "lib/problems/classical-mechanics/oscillators-everywhere/oscillators-everywhere-challenge-coupled-pendulum-normal-modes.ts",
  },
  {
    id: "oscillators-everywhere-exam-shm-position-velocity-acceleration",
    primaryTopicSlug: "oscillators-everywhere",
    relatedTopicSlugs: [],
    difficulty: "exam",
    equationSlugs: ["simple-harmonic-motion", "shm-position", "shm-velocity", "shm-acceleration", "shm-energy"],
    inputs: { A: { value: 0.2, units: "m" }, omega: { value: 4, units: "rad/s" }, phi: { value: 1.0472, units: "rad" }, m: { value: 0.5, units: "kg" }, t: { value: 0.8, units: "s" } },
    steps: [
      { id: "k", varName: "k", canonicalExpr: "m * omega^2", units: "N/m",
        inputDomain: { omega: [1, 20], m: [0.1, 5] }, toleranceRel: 1e-6 },
      { id: "x", varName: "x", canonicalExpr: "A * cos(omega * t + phi)", units: "m",
        inputDomain: { A: [0.01, 0.5], omega: [1, 20], t: [0, 5], phi: [0, 1.5] }, toleranceRel: 1e-6 },
      { id: "v", varName: "v", canonicalExpr: "-A * omega * sin(omega * t + phi)", units: "m/s",
        inputDomain: { A: [0.01, 0.5], omega: [1, 20], t: [0, 5], phi: [0, 1.5] }, toleranceRel: 1e-6 },
      { id: "a_accel", varName: "a", canonicalExpr: "-A * omega^2 * cos(omega * t + phi)", units: "m/s²",
        inputDomain: { A: [0.01, 0.5], omega: [1, 20], t: [0, 5], phi: [0, 1.5] }, toleranceRel: 1e-6 },
      { id: "E_total", varName: "E", canonicalExpr: "0.5 * m * omega^2 * A^2", units: "J",
        inputDomain: { A: [0.01, 0.5], omega: [1, 20], m: [0.1, 5] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "x",
    solverPath: "lib/problems/classical-mechanics/oscillators-everywhere/oscillators-everywhere-exam-shm-position-velocity-acceleration.ts",
  },

  // damped-and-driven-oscillations (5) — schema fixes applied
  {
    id: "damped-and-driven-oscillations-easy-amplitude-decay-after-n-cycles",
    primaryTopicSlug: "damped-and-driven-oscillations",
    relatedTopicSlugs: [],
    difficulty: "easy",
    equationSlugs: ["damped-natural-frequency", "damped-amplitude-decay"],
    inputs: { A_0: { value: 0.20, units: "m" }, gamma: { value: 0.4, units: "rad/s" }, omega_0: { value: 5, units: "rad/s" }, n: { value: 8, units: "" } },
    steps: [
      { id: "omega_d", varName: "omega_d", canonicalExpr: "sqrt(omega_0^2 - gamma^2 / 4)", units: "rad/s",
        inputDomain: { gamma: [0.1, 2], omega_0: [1, 20] }, toleranceRel: 1e-6 },
      { id: "T_d", varName: "T_d", canonicalExpr: "2 * PI / sqrt(omega_0^2 - gamma^2 / 4)", units: "s",
        inputDomain: { gamma: [0.1, 2], omega_0: [1, 20] }, toleranceRel: 1e-6 },
      { id: "t_n", varName: "t_n", canonicalExpr: "n * 2 * PI / sqrt(omega_0^2 - gamma^2 / 4)", units: "s",
        inputDomain: { gamma: [0.1, 2], omega_0: [1, 20], n: [1, 20] }, toleranceRel: 1e-6 },
      { id: "A", varName: "A",
        canonicalExpr: "A_0 * exp(-gamma * n * 2 * PI / sqrt(omega_0^2 - gamma^2 / 4) / 2)",
        units: "m", inputDomain: { A_0: [0.01, 0.5], gamma: [0.1, 2], omega_0: [1, 20], n: [1, 20] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "A",
    solverPath: "lib/problems/classical-mechanics/damped-and-driven-oscillations/damped-and-driven-oscillations-easy-amplitude-decay-after-n-cycles.ts",
  },
  {
    id: "damped-and-driven-oscillations-medium-q-factor-from-bandwidth",
    primaryTopicSlug: "damped-and-driven-oscillations",
    relatedTopicSlugs: [],
    difficulty: "medium",
    equationSlugs: ["q-factor", "damped-natural-frequency"],
    inputs: { omega_0: { value: 2764.601, units: "rad/s" }, gamma: { value: 8.796, units: "rad/s" } },
    steps: [
      { id: "Q", varName: "Q", canonicalExpr: "omega_0 / gamma", units: "",
        inputDomain: { gamma: [0.1, 100], omega_0: [10, 5000] }, toleranceRel: 1e-6 },
      { id: "t_e", varName: "t_e", canonicalExpr: "2 / gamma", units: "s",
        inputDomain: { gamma: [0.1, 100] }, toleranceRel: 1e-6 },
      { id: "delta_omega", varName: "delta_omega", canonicalExpr: "gamma", units: "rad/s",
        inputDomain: { gamma: [0.1, 100] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "delta_omega",
    solverPath: "lib/problems/classical-mechanics/damped-and-driven-oscillations/damped-and-driven-oscillations-medium-q-factor-from-bandwidth.ts",
  },
  {
    id: "damped-and-driven-oscillations-hard-resonant-amplitude-with-q",
    primaryTopicSlug: "damped-and-driven-oscillations",
    relatedTopicSlugs: [],
    difficulty: "hard",
    equationSlugs: ["driven-oscillator-amplitude", "resonance", "q-factor"],
    inputs: { omega_0: { value: 10, units: "rad/s" }, Q_given: { value: 8, units: "" }, F_0: { value: 4, units: "N" }, m: { value: 0.5, units: "kg" }, omega_d: { value: 6, units: "rad/s" } },
    steps: [
      { id: "gamma", varName: "gamma", canonicalExpr: "omega_0 / Q_given", units: "rad/s",
        inputDomain: { omega_0: [1, 20], Q_given: [1, 50] }, toleranceRel: 1e-6 },
      { id: "F_per_m", varName: "F_per_m", canonicalExpr: "F_0 / m", units: "m/s²",
        inputDomain: { F_0: [1, 50], m: [0.1, 5] }, toleranceRel: 1e-6 },
      { id: "A_res", varName: "A_res", canonicalExpr: "(F_0 / m) / ((omega_0 / Q_given) * omega_0)", units: "m",
        inputDomain: { F_0: [1, 50], m: [0.1, 5], omega_0: [1, 20], Q_given: [1, 50] }, toleranceRel: 1e-6 },
      { id: "A_off", varName: "A_off",
        canonicalExpr: "(F_0 / m) / sqrt((omega_0^2 - omega_d^2)^2 + ((omega_0 / Q_given) * omega_d)^2)",
        units: "m", inputDomain: { F_0: [1, 50], m: [0.1, 5], omega_0: [5, 20], Q_given: [1, 50], omega_d: [1, 20] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "A_off",
    solverPath: "lib/problems/classical-mechanics/damped-and-driven-oscillations/damped-and-driven-oscillations-hard-resonant-amplitude-with-q.ts",
  },
  {
    id: "damped-and-driven-oscillations-challenge-critical-vs-underdamped-ringdown",
    primaryTopicSlug: "damped-and-driven-oscillations",
    relatedTopicSlugs: [],
    difficulty: "challenge",
    equationSlugs: ["damped-oscillator-position", "damped-natural-frequency"],
    inputs: { k: { value: 16, units: "N/m" }, m: { value: 1, units: "kg" }, x_0: { value: 0.25, units: "m" }, gamma: { value: 1, units: "rad/s" }, t: { value: 2, units: "s" } },
    steps: [
      { id: "omega_0", varName: "omega_0", canonicalExpr: "sqrt(k / m)", units: "rad/s",
        inputDomain: { k: [4, 100], m: [0.1, 5] }, toleranceRel: 1e-6 },
      { id: "gamma_crit", varName: "gamma_crit", canonicalExpr: "2 * sqrt(k / m)", units: "rad/s",
        inputDomain: { k: [4, 100], m: [0.1, 5] }, toleranceRel: 1e-6 },
      { id: "energy_frac", varName: "energy_frac", canonicalExpr: "exp(-gamma * t)", units: "",
        inputDomain: { gamma: [0.5, 5], t: [0.5, 5] }, toleranceRel: 1e-6 },
      { id: "x_crit_2", varName: "x_crit",
        canonicalExpr: "x_0 * exp(-2 * sqrt(k / m) * t / 2) * (1 + 2 * sqrt(k / m) * t / 2)",
        units: "m", inputDomain: { x_0: [0.05, 0.5], k: [4, 100], m: [0.1, 5], t: [0.5, 5] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "x_crit_2",
    solverPath: "lib/problems/classical-mechanics/damped-and-driven-oscillations/damped-and-driven-oscillations-challenge-critical-vs-underdamped-ringdown.ts",
  },
  {
    id: "damped-and-driven-oscillations-exam-driven-amplitude-vs-frequency",
    primaryTopicSlug: "damped-and-driven-oscillations",
    relatedTopicSlugs: [],
    difficulty: "exam",
    equationSlugs: ["driven-oscillator-amplitude", "resonance", "q-factor", "damped-natural-frequency"],
    inputs: { m: { value: 2, units: "kg" }, omega_0: { value: 8, units: "rad/s" }, gamma: { value: 2, units: "rad/s" }, F_0: { value: 20, units: "N" }, omega_d: { value: 8, units: "rad/s" } },
    steps: [
      { id: "Q", varName: "Q", canonicalExpr: "omega_0 / gamma", units: "",
        inputDomain: { gamma: [0.5, 5], omega_0: [1, 20] }, toleranceRel: 1e-6 },
      { id: "F_per_m", varName: "F_per_m", canonicalExpr: "F_0 / m", units: "m/s²",
        inputDomain: { F_0: [1, 50], m: [0.1, 5] }, toleranceRel: 1e-6 },
      { id: "A_res", varName: "A_res", canonicalExpr: "(F_0 / m) / (gamma * omega_0)", units: "m",
        inputDomain: { F_0: [1, 50], m: [0.1, 5], gamma: [0.5, 5], omega_0: [1, 20] }, toleranceRel: 1e-6 },
      { id: "A_static", varName: "A_static", canonicalExpr: "(F_0 / m) / omega_0^2", units: "m",
        inputDomain: { F_0: [1, 50], m: [0.1, 5], omega_0: [1, 20] }, toleranceRel: 1e-6 },
      { id: "Q_factor_ratio", varName: "Q_ratio", canonicalExpr: "omega_0 / gamma", units: "",
        inputDomain: { gamma: [0.5, 5], omega_0: [1, 20] }, toleranceRel: 1e-6 },
    ],
    finalAnswerStepId: "Q_factor_ratio",
    solverPath: "lib/problems/classical-mechanics/damped-and-driven-oscillations/damped-and-driven-oscillations-exam-driven-amplitude-vs-frequency.ts",
  },
];

export function getProblem(id: string): Problem | undefined {
  return PROBLEMS.find((p) => p.id === id);
}

export function getProblemsForTopic(topicSlug: string): readonly Problem[] {
  return PROBLEMS.filter(
    (p) =>
      p.primaryTopicSlug === topicSlug ||
      p.relatedTopicSlugs.includes(topicSlug),
  );
}

export function getProblemsByEquation(equationSlug: string): readonly Problem[] {
  return PROBLEMS.filter((p) => p.equationSlugs.includes(equationSlug));
}
