/**
 * Irreversibility, Loschmidt reversal, and Landauer erasure (FIG.13).
 *
 * Two pieces of physics for the arrow-of-time topic:
 *
 *  1. A microscopically *time-reversible* 1-D gas. Particles stream in a box
 *     with elastic wall reflections; `stepParticles` advances them, `reverse`
 *     flips every velocity. With exact arithmetic, stepping forward, reversing,
 *     and stepping the same number of times returns the gas to its start — this
 *     is Loschmidt's objection made literal. A tiny `perturb` models the
 *     floating-point round-off that, in any real simulation, destroys the
 *     reversal and lets the gas re-mix.
 *
 *  2. A *coarse-grained* (observational) entropy, the quantity that actually
 *     has an arrow: the Boltzmann entropy ln Ω of the left/right occupancy
 *     macrostate. Fine-grained microstate information is conserved under
 *     reversal; this coarse entropy is not.
 *
 *  3. Landauer's bound: erasing one bit of the demon's memory dissipates at
 *     least k_B ln 2 of entropy — the bookkeeping that rescues the Second Law
 *     from Maxwell's demon (resolution deferred to FIG.20).
 *
 * Pure functions over plain data; no React.
 */

import { BOLTZMANN_K } from "./boltzmann-entropy";
import { lnBinomial } from "./multiplicity";
import type { Rng } from "./random";
import { gaussian } from "./random";

/** A 1-D particle: position x ∈ [0, 1] and velocity v (box units per second). */
export interface Particle1D {
  x: number;
  v: number;
}

/**
 * Advance every particle by dt with elastic reflection off the walls at x = 0
 * and x = 1. Returns a new array; inputs are not mutated, so a scene can keep
 * the pre-step state for an undo/reverse.
 *
 * Reflection is resolved by folding the position back into [0, 1] and flipping
 * the velocity sign for each wall crossing, so even large dt stays in-bounds.
 */
export function stepParticles(
  particles: readonly Particle1D[],
  dt: number,
): Particle1D[] {
  return particles.map(({ x, v }) => {
    let nx = x + v * dt;
    let nv = v;
    // Fold into [0, 1] with the standard triangle-wave reflection.
    if (nx < 0 || nx > 1) {
      const period = Math.floor(nx);
      let frac = nx - period; // in [0, 1)
      // Odd number of reflections flips both position and velocity sense.
      if (((period % 2) + 2) % 2 === 1) {
        frac = 1 - frac;
      }
      // Velocity sign: each unit interval crossed flips it once.
      if (((period % 2) + 2) % 2 !== 0) nv = -nv;
      nx = frac;
    }
    return { x: nx, v: nv };
  });
}

/** Flip the velocity of every particle — Loschmidt's "reverse all velocities". */
export function reverse(particles: readonly Particle1D[]): Particle1D[] {
  return particles.map(({ x, v }) => ({ x, v: -v }));
}

/**
 * Add a minute Gaussian jolt to every velocity, modelling the round-off error
 * that makes a real reversal imperfect. `epsilon` is the standard deviation;
 * with epsilon = 0 the gas is left untouched (perfect reversibility).
 */
export function perturb(
  particles: readonly Particle1D[],
  epsilon: number,
  rng: Rng,
): Particle1D[] {
  if (epsilon === 0) return particles.map((p) => ({ ...p }));
  return particles.map(({ x, v }) => ({ x, v: v + gaussian(rng, 0, epsilon) }));
}

/** Count particles in the left half (x < 0.5) — the macrostate variable. */
export function leftCount(particles: readonly Particle1D[]): number {
  let n = 0;
  for (const p of particles) if (p.x < 0.5) n++;
  return n;
}

/**
 * Coarse-grained Boltzmann entropy of the left/right occupancy, in units of
 * k_B: ln C(N, k) where k particles are on the left. Maximal at k = N/2
 * (well-mixed), zero when all particles crowd one side. This is the curve that
 * rises, dips during a successful reversal, and rises again once round-off wins.
 */
export function occupancyEntropy(particles: readonly Particle1D[]): number {
  const n = particles.length;
  const k = leftCount(particles);
  return lnBinomial(n, k);
}

/**
 * Shannon entropy of an arbitrary coarse-graining into bins, in units of k_B:
 * −Σ pᵢ ln pᵢ over occupied bins (pᵢ = countᵢ / N). A finer-grained companion
 * to {@link occupancyEntropy} for histograms with more than two boxes.
 */
export function binEntropy(counts: readonly number[]): number {
  const total = counts.reduce((a, c) => a + c, 0);
  if (total === 0) return 0;
  let s = 0;
  for (const c of counts) {
    if (c > 0) {
      const p = c / total;
      s -= p * Math.log(p);
    }
  }
  return s;
}

/**
 * Landauer's bound: the minimum entropy generated by erasing `bits` bits of
 * memory, ΔS = bits · k_B ln 2 (J/K). The demon's apparent Second-Law
 * violation is paid for here.
 */
export function landauerErasureCost(bits: number): number {
  return bits * BOLTZMANN_K * Math.LN2;
}

/** The same bound expressed in units of k_B (i.e. bits · ln 2). */
export function erasureCostInUnitsOfK(bits: number): number {
  return bits * Math.LN2;
}
